# Generated by Django 5.2.6 on 2026-03-08 02:13

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('estimate_id', models.AutoField(primary_key=True, serialize=False)),
                ('estimate_number', models.CharField(max_length=50)),
                ('version', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('superseded', 'Superseded')], default='draft', max_length=20)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('closed_date', models.DateTimeField(blank=True, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'estimates',
            },
        ),
        migrations.CreateModel(
            name='EstimateLineItem',
            fields=[
                ('line_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('line_number', models.PositiveIntegerField(blank=True, null=True)),
                ('qty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('units', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('taxable_override', models.BooleanField(blank=True, null=True)),
                ('tax_rate_override', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
            ],
            options={
                'verbose_name': 'Estimate Line Item',
                'verbose_name_plural': 'Estimate Line Items',
                'db_table': 'est_li',
            },
        ),
        migrations.CreateModel(
            name='EstWorksheet',
            fields=[
                ('est_worksheet_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('final', 'Final'), ('superseded', 'Superseded')], default='draft', max_length=20)),
                ('version', models.IntegerField(default=1)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'worksheets',
            },
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('template_id', models.AutoField(primary_key=True, serialize=False)),
                ('template_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('units', models.CharField(blank=True, max_length=50)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'task_templates',
            },
        ),
        migrations.CreateModel(
            name='TemplateBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'template_bundles',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TemplateTaskAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_qty', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('sort_order', models.IntegerField(default=0)),
                ('mapping_strategy', models.CharField(choices=[('direct', 'Direct - becomes its own line item'), ('bundle', 'Bundle - part of a bundled line item'), ('exclude', 'Exclude - internal only, not on estimate')], default='direct', max_length=20)),
            ],
            options={
                'db_table': 'template_task_assoc',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderTemplate',
            fields=[
                ('template_id', models.AutoField(primary_key=True, serialize=False)),
                ('template_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'wo_templates',
            },
        ),
    ]
