# Generated by Django 5.2.6 on 2026-10-06 21:05

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeOrder',
            fields=[
                ('change_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('change_order_number', models.CharField(blank=True, max_length=80, unique=True)),
                ('version', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('superseded', 'Superseded')], default='draft', max_length=20)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('closed_date', models.DateTimeField(blank=True, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('public_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
            ],
            options={
                'db_table': 'change_orders',
            },
        ),
        migrations.CreateModel(
            name='ChangeOrderLineItem',
            fields=[
                ('line_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('line_number', models.PositiveIntegerField(blank=True, null=True)),
                ('qty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('units', models.CharField(default='none', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_comment', models.BooleanField(default=False, help_text='Informational line only — no charge, not linked to any task/atom.')),
                ('action', models.CharField(choices=[('add', 'Add'), ('remove', 'Remove'), ('replace', 'Replace')], max_length=10)),
                ('is_material', models.BooleanField(default=False, help_text='Marks a bare (no inventory_item) freeform line as a material: at CO acceptance it crystallizes into a provisional Material (sell price only, no lot); non-material bare lines stay document-only. Mirrors EstimateLineItem.is_material.')),
                ('adjustment_percent', models.DecimalField(blank=True, decimal_places=2, help_text="Snapshot of adjustment_service's rate at creation time. compute_adjustment_amount reads this field, never the live scheme.", max_digits=6, null=True)),
                ('per_unit', models.BooleanField(default=False, help_text="This line's claimed atoms describe ONE unit of qty (per-unit-lines spec §2), not the whole-job total. Mirrors EstimateLineItem.per_unit.")),
            ],
            options={
                'db_table': 'co_li',
            },
        ),
        migrations.CreateModel(
            name='ChangeOrderLineItemSource',
            fields=[
                ('source_id', models.AutoField(primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('task', 'Task'), ('material', 'Material')], max_length=20)),
                ('source_pk', models.PositiveIntegerField()),
                ('per_unit_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('per_unit_worker_time', models.DurationField(blank=True, null=True)),
            ],
            options={
                'db_table': 'co_li_sources',
            },
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('estimate_id', models.AutoField(primary_key=True, serialize=False)),
                ('estimate_number', models.CharField(max_length=50)),
                ('version', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('superseded', 'Superseded')], default='draft', max_length=20)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('closed_date', models.DateTimeField(blank=True, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('public_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
            ],
            options={
                'db_table': 'estimates',
            },
        ),
        migrations.CreateModel(
            name='EstimateLineItem',
            fields=[
                ('line_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('line_number', models.PositiveIntegerField(blank=True, null=True)),
                ('qty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('units', models.CharField(default='none', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_comment', models.BooleanField(default=False, help_text='Informational line only — no charge, not linked to any task/atom.')),
                ('adjustment_percent', models.DecimalField(blank=True, decimal_places=2, help_text="Snapshot of adjustment_service's rate at creation time. compute_adjustment_amount reads this field, never the live scheme.", max_digits=6, null=True)),
                ('is_material', models.BooleanField(default=False, help_text='Marks a bare (no inventory_item, non-adjustment) freeform line as a material: at acceptance it crystallizes into a provisional Material (sell price only, no lot); non-material bare lines stay document-only.')),
                ('work_declined', models.BooleanField(default=False, help_text='The "no work needed" answer on the acceptance checklist: a job manager marks a plain hand line (no sources, not an adjustment, not a deposit line, no catalog identity) as declined instead of minting a task from it. Set-able only while the estimate is accepted; reversible (false = unanswered again).')),
                ('per_unit', models.BooleanField(default=False, help_text="This line's claimed atoms describe ONE unit of qty (per-unit-lines spec §2), not the whole-job total. Atoms themselves always store whole-job totals; the per-unit snapshot lives on claim source rows.")),
            ],
            options={
                'verbose_name': 'Estimate Line Item',
                'verbose_name_plural': 'Estimate Line Items',
                'db_table': 'est_li',
            },
        ),
        migrations.CreateModel(
            name='EstimateLineItemSource',
            fields=[
                ('source_id', models.AutoField(primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('task', 'Task'), ('material', 'Material')], max_length=20)),
                ('source_pk', models.PositiveIntegerField()),
                ('per_unit_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('per_unit_worker_time', models.DurationField(blank=True, null=True)),
            ],
            options={
                'db_table': 'estimate_line_item_sources',
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('template_id', models.AutoField(primary_key=True, serialize=False)),
                ('template_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('qbo_id', models.CharField(blank=True, default='', max_length=50)),
                ('default_active_modifiers', models.JSONField(blank=True, default=list, help_text='Pre-checked modifier keys from the scheme')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'service_items',
            },
        ),
        migrations.CreateModel(
            name='TemplateTaskAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_qty', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'template_task_assoc',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='WorkTemplate',
            fields=[
                ('template_id', models.AutoField(primary_key=True, serialize=False)),
                ('template_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'work_templates',
            },
        ),
    ]
