# Generated by Django 5.2.6 on 2026-10-06 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('estimates', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeorder',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_orders', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='changeorder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='estimates.changeorder'),
        ),
        migrations.AddField(
            model_name='changeorderlineitem',
            name='accounting_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to='core.accountingcategory'),
        ),
        migrations.AddField(
            model_name='changeorderlineitem',
            name='adjustment_service',
            field=models.ForeignKey(blank=True, help_text='Set when this line is a percentage adjustment (rush/discount).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='jobs.ratescheme'),
        ),
        migrations.AddField(
            model_name='changeorderlineitem',
            name='adjustment_target_categories',
            field=models.ManyToManyField(blank=True, help_text='Categories the adjustment applies to; empty = all non-adjustment lines.', related_name='+', to='core.accountingcategory'),
        ),
        migrations.AddField(
            model_name='changeorderlineitem',
            name='change_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimates.changeorder'),
        ),
    ]
