# Generated by Django 5.2.6 on 2026-03-08 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('estimates', '0001_initial'),
        ('inventory', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='estimates.estimate'),
        ),
        migrations.AddField(
            model_name='estimatelineitem',
            name='estimate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimates.estimate'),
        ),
        migrations.AddField(
            model_name='estimatelineitem',
            name='line_item_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to='core.lineitemtype'),
        ),
        migrations.AddField(
            model_name='estimatelineitem',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.material'),
        ),
        migrations.AddField(
            model_name='estimatelineitem',
            name='price_list_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.pricelistitem'),
        ),
        migrations.AddField(
            model_name='estimatelineitem',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='jobs.task'),
        ),
        migrations.AddField(
            model_name='estworksheet',
            name='estimate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worksheets', to='estimates.estimate'),
        ),
        migrations.AddField(
            model_name='estworksheet',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
        ),
        migrations.AddField(
            model_name='estworksheet',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='estimates.estworksheet'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='line_item_type',
            field=models.ForeignKey(blank=True, help_text='Type of line item this task produces when mapped directly', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.lineitemtype'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='parent_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_templates', to='estimates.tasktemplate'),
        ),
        migrations.AddField(
            model_name='templatebundle',
            name='line_item_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.lineitemtype'),
        ),
        migrations.AddField(
            model_name='templatetaskassociation',
            name='bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associations', to='estimates.templatebundle'),
        ),
        migrations.AddField(
            model_name='templatetaskassociation',
            name='task_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimates.tasktemplate'),
        ),
        migrations.AddField(
            model_name='templatetaskassociation',
            name='work_order_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimates.workordertemplate'),
        ),
        migrations.AddField(
            model_name='templatebundle',
            name='work_order_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='estimates.workordertemplate'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='work_order_templates',
            field=models.ManyToManyField(related_name='task_templates', through='estimates.TemplateTaskAssociation', to='estimates.workordertemplate'),
        ),
        migrations.AddField(
            model_name='estworksheet',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estimates.workordertemplate'),
        ),
        migrations.AlterUniqueTogether(
            name='estimate',
            unique_together={('estimate_number', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='templatetaskassociation',
            unique_together={('work_order_template', 'task_template')},
        ),
        migrations.AlterUniqueTogether(
            name='templatebundle',
            unique_together={('work_order_template', 'name')},
        ),
    ]
