# Generated by Django 5.2.6 on 2026-10-06 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('estimates', '0002_initial'),
        ('inventory', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeorderlineitem',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='changeorderlineitemsource',
            name='change_order_line_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='estimates.changeorderlineitem'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='estimates.estimate'),
        ),
        migrations.AddField(
            model_name='changeorder',
            name='estimate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_orders', to='estimates.estimate'),
        ),
        migrations.AddField(
            model_name='estimatelineitem',
            name='accounting_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to='core.accountingcategory'),
        ),
        migrations.AddField(
            model_name='estimatelineitem',
            name='adjustment_service',
            field=models.ForeignKey(blank=True, help_text='Set when this line is a percentage adjustment (rush/discount).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='jobs.ratescheme'),
        ),
        migrations.AddField(
            model_name='estimatelineitem',
            name='adjustment_target_categories',
            field=models.ManyToManyField(blank=True, help_text='Categories the adjustment applies to; empty = all non-adjustment lines.', related_name='+', to='core.accountingcategory'),
        ),
        migrations.AddField(
            model_name='estimatelineitem',
            name='estimate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimates.estimate'),
        ),
        migrations.AddField(
            model_name='estimatelineitem',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='changeorderlineitem',
            name='target_line_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='co_amendments', to='estimates.estimatelineitem'),
        ),
        migrations.AddField(
            model_name='estimatelineitemsource',
            name='estimate_line_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='estimates.estimatelineitem'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='rate_scheme',
            field=models.ForeignKey(help_text='Default billing scheme for tasks from this template', on_delete=django.db.models.deletion.PROTECT, to='jobs.ratescheme'),
        ),
        migrations.AddField(
            model_name='estimatelineitem',
            name='service_item',
            field=models.ForeignKey(blank=True, help_text='Deferred service descriptor: crystallizes to a Task at acceptance.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='estimates.serviceitem'),
        ),
        migrations.AddField(
            model_name='changeorderlineitem',
            name='service_item',
            field=models.ForeignKey(blank=True, help_text='Deferred service descriptor: crystallizes to a Task at CO acceptance.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='estimates.serviceitem'),
        ),
        migrations.AddField(
            model_name='templatetaskassociation',
            name='service_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimates.serviceitem'),
        ),
        migrations.AddField(
            model_name='templatetaskassociation',
            name='work_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimates.worktemplate'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='work_templates',
            field=models.ManyToManyField(related_name='service_items', through='estimates.TemplateTaskAssociation', to='estimates.worktemplate'),
        ),
        migrations.AlterUniqueTogether(
            name='changeorderlineitemsource',
            unique_together={('source_type', 'source_pk')},
        ),
        migrations.AlterUniqueTogether(
            name='estimate',
            unique_together={('estimate_number', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='estimatelineitemsource',
            unique_together={('source_type', 'source_pk')},
        ),
        migrations.AlterUniqueTogether(
            name='templatetaskassociation',
            unique_together={('work_template', 'service_item')},
        ),
    ]
