# Generated by Django 5.2.6 on 2026-03-31 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0003_rename_line_item_type_estimatelineitem_accounting_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatelineitem',
            name='units',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='units',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
