# Generated by Django 5.2.6 on 2026-04-05 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0004_alter_estimatelineitem_units_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasktemplate',
            name='parent_template',
        ),
    ]
