# Generated by Django 5.2.6 on 2026-04-05 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0005_remove_tasktemplate_parent_template'),
        ('jobs', '0009_task_split_data_move'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatelineitem',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='jobs.plantask'),
        ),
    ]
