# Generated by Django 5.2.6 on 2026-04-05 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0006_alter_estimatelineitem_task'),
        ('inventory', '0006_planmaterial_plan_task_planmaterial_price_list_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatelineitem',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.planmaterial'),
        ),
    ]
