# Generated by Django 5.2.6 on 2026-04-06 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0007_alter_estimatelineitem_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatebundle',
            name='description',
        ),
    ]
