# Generated by Django 5.2.6 on 2026-04-13 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0008_remove_templatebundle_description'),
        ('jobs', '0011_task_blocked_reason'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkOrderTemplate',
            new_name='WorkTemplate',
        ),
        migrations.RenameField(
            model_name='tasktemplate',
            old_name='work_order_templates',
            new_name='work_templates',
        ),
        migrations.RenameField(
            model_name='templatebundle',
            old_name='work_order_template',
            new_name='work_template',
        ),
        migrations.RenameField(
            model_name='templatetaskassociation',
            old_name='work_order_template',
            new_name='work_template',
        ),
        migrations.AlterUniqueTogether(
            name='templatebundle',
            unique_together={('work_template', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='templatetaskassociation',
            unique_together={('work_template', 'task_template')},
        ),
        migrations.AlterModelTable(
            name='worktemplate',
            table='work_templates',
        ),
    ]
