# Generated by Django 5.2.6 on 2026-04-17 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0009_rename_workordertemplate_worktemplate_and_more'),
        ('jobs', '0015_est_worker_time_source_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktemplate',
            name='default_active_modifiers',
            field=models.JSONField(blank=True, default=list, help_text='Pre-checked modifier keys from the scheme'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='default_billable_qty',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Typical estimated billable quantity', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='rate_scheme',
            field=models.ForeignKey(blank=True, help_text='Default billing scheme for tasks from this template', null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.ratescheme'),
        ),
    ]
