# Generated by Django 5.2.6 on 2026-04-20 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0010_tasktemplate_rate_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatelineitem',
            name='source_template',
            field=models.ForeignKey(blank=True, help_text='TaskTemplate this line item was created from (preserves catalog ref for direct-estimate carry-over).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='estimates.tasktemplate'),
        ),
    ]
