# Generated by Django 5.2.6 on 2026-04-20 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0011_estimateLineItem_source_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimateLineItemSource',
            fields=[
                ('source_id', models.AutoField(primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('plan_charge', 'PlanCharge'), ('plan_material', 'PlanMaterial')], max_length=20)),
                ('source_pk', models.PositiveIntegerField()),
                ('estimate_line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='estimates.estimatelineitem')),
            ],
            options={
                'db_table': 'estimate_line_item_sources',
                'unique_together': {('source_type', 'source_pk')},
            },
        ),
    ]
