# Generated by Django 5.2.6 on 2026-04-20 19:14

from django.db import migrations


def back_fill_sources(apps, schema_editor):
    EstimateLineItem = apps.get_model('estimates', 'EstimateLineItem')
    EstimateLineItemSource = apps.get_model('estimates', 'EstimateLineItemSource')
    PlanCharge = apps.get_model('jobs', 'PlanCharge')

    for li in EstimateLineItem.objects.all():
        # Skip if already has source rows (idempotent)
        if EstimateLineItemSource.objects.filter(estimate_line_item=li).exists():
            continue
        if li.task_id:
            # task FK is to PlanTask; the atom is the OneToOne PlanCharge off it
            try:
                pc = PlanCharge.objects.get(plan_task_id=li.task_id)
            except PlanCharge.DoesNotExist:
                continue  # PlanTask without a PlanCharge — nothing to claim
            EstimateLineItemSource.objects.create(
                estimate_line_item=li,
                source_type='plan_charge',
                source_pk=pc.pk,
            )
        elif li.material_id:
            EstimateLineItemSource.objects.create(
                estimate_line_item=li,
                source_type='plan_material',
                source_pk=li.material_id,
            )


def reverse_back_fill(apps, schema_editor):
    # Conservative reverse: delete all source rows
    # (Safe because this was a pre-production back-fill)
    EstimateLineItemSource = apps.get_model('estimates', 'EstimateLineItemSource')
    EstimateLineItemSource.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0012_estimateLineItemSource'),
        ('jobs', '0014_taskcharge_plancharge'),
    ]

    run_before = [
        ('jobs', '0024_drop_plan_charge_and_source_plan_charge'),
    ]

    operations = [
        migrations.RunPython(back_fill_sources, reverse_back_fill),
    ]
