# Generated by Django 5.2.6 on 2026-04-20 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0013_backfill_estimate_line_item_source'),
        ('jobs', '0018_drop_plan_bundle_and_mapping_strategy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatetaskassociation',
            name='bundle',
        ),
        migrations.RemoveField(
            model_name='templatetaskassociation',
            name='mapping_strategy',
        ),
        migrations.DeleteModel(
            name='TemplateBundle',
        ),
    ]
