# Generated by Django 5.2.6 on 2026-04-20 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0014_drop_template_bundle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimatelineitem',
            name='material',
        ),
        migrations.RemoveField(
            model_name='estimatelineitem',
            name='task',
        ),
    ]
