# Generated by Django 5.2.6 on 2026-05-02 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0015_drop_estimate_line_item_legacy_fks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatelineitemsource',
            name='source_type',
            field=models.CharField(choices=[('plan_task', 'PlanTask'), ('plan_material', 'PlanMaterial')], max_length=20),
        ),
    ]
