# Generated by Django 5.2.6 on 2026-05-03 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0017_rewrite_source_type_to_plan_task'),
        ('jobs', '0029_planTask_billing_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktemplate',
            name='default_billable_qty',
            field=models.DecimalField(decimal_places=2, help_text='Typical estimated billable quantity', max_digits=10),
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='rate_scheme',
            field=models.ForeignKey(help_text='Default billing scheme for tasks from this template', on_delete=django.db.models.deletion.PROTECT, to='jobs.ratescheme'),
        ),
    ]
