# Generated by Django 5.2.6 on 2026-05-04 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0018_tasktemplate_billing_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasktemplate',
            name='accounting_category',
        ),
        migrations.RemoveField(
            model_name='tasktemplate',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='tasktemplate',
            name='units',
        ),
    ]
