# Generated by Django 5.2.6 on 2026-05-13 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0019_drop_workitem_ac_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estworksheet',
            name='template',
        ),
        migrations.RemoveField(
            model_name='worktemplate',
            name='is_active',
        ),
    ]
