# Generated by Django 5.2.6 on 2026-05-26 15:43

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_scheduledprocessrun'),
        ('estimates', '0020_remove_estworksheet_template_and_more'),
        ('inventory', '0025_pricelistitem_price_list_qty_on_hand_non_negative'),
        ('jobs', '0039_backfill_job_accent_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeOrder',
            fields=[
                ('change_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('change_order_number', models.CharField(blank=True, max_length=80, unique=True)),
                ('version', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('superseded', 'Superseded')], default='draft', max_length=20)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('closed_date', models.DateTimeField(blank=True, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_orders', to='estimates.estimate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_orders', to='jobs.job')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='estimates.changeorder')),
            ],
            options={
                'db_table': 'change_orders',
            },
        ),
        migrations.CreateModel(
            name='ChangeOrderLineItem',
            fields=[
                ('line_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('line_number', models.PositiveIntegerField(blank=True, null=True)),
                ('qty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('units', models.CharField(default='none', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('taxable_override', models.BooleanField(blank=True, null=True)),
                ('tax_rate_override', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('action', models.CharField(choices=[('add', 'Add'), ('remove', 'Remove'), ('replace', 'Replace')], max_length=10)),
                ('accounting_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to='core.accountingcategory')),
                ('change_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimates.changeorder')),
                ('price_list_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.pricelistitem')),
                ('source_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estimates.tasktemplate')),
                ('target_line_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='co_amendments', to='estimates.estimatelineitem')),
            ],
            options={
                'db_table': 'co_li',
            },
        ),
    ]
