# Generated by Django 5.2.6 on 2026-06-03 15:30

from django.db import migrations


def delete_superseded_worksheets(apps, schema_editor):
    """Collapse to one worksheet per job: drop legacy superseded worksheet
    versions before the version/status columns disappear. Runs while the
    `status` column still exists."""
    EstWorksheet = apps.get_model('estimates', 'EstWorksheet')
    EstWorksheet.objects.filter(status='superseded').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0022_estimate_public_token'),
    ]

    operations = [
        migrations.RunPython(
            delete_superseded_worksheets,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='estworksheet',
            name='estimate',
        ),
        migrations.RemoveField(
            model_name='estworksheet',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='estworksheet',
            name='status',
        ),
        migrations.RemoveField(
            model_name='estworksheet',
            name='version',
        ),
    ]
