# Generated by Django 5.2.6 on 2026-06-08 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0023_remove_estworksheet_estimate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeorder',
            name='public_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
