# Generated by Django 5.2.6 on 2026-06-16 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0024_changeorder_public_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='changeorderlineitem',
            old_name='price_list_item',
            new_name='inventory_item',
        ),
        migrations.RenameField(
            model_name='estimatelineitem',
            old_name='price_list_item',
            new_name='inventory_item',
        ),
    ]
