# Generated by Django 5.2.6 on 2026-06-25 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0028_rename_tasktemplate_service_item'),
        ('jobs', '0047_rename_serviceprice_to_serviceitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatelineitem',
            name='adjustment_service',
            field=models.ForeignKey(blank=True, help_text='Set when this line is a percentage adjustment (rush/discount).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='jobs.serviceitem'),
        ),
    ]
