# Generated by Django 5.2.6 on 2026-06-27 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0031_rename_tasktemplate_to_serviceitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatelineitem',
            name='source_template',
            field=models.ForeignKey(blank=True, help_text='ServiceItem this line item was created from (preserves catalog ref for direct-estimate carry-over).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='estimates.serviceitem'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='work_templates',
            field=models.ManyToManyField(related_name='service_items', through='estimates.TemplateTaskAssociation', to='estimates.worktemplate'),
        ),
    ]
