# Generated by Django 5.2.6 on 2026-06-27 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0032_alter_estimatelineitem_source_template_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceitem',
            name='default_billable_qty',
        ),
    ]
