# Generated by Django 5.2.6 on 2026-06-28 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0033_remove_serviceitem_default_billable_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changeorderlineitem',
            name='source_template',
        ),
        migrations.RemoveField(
            model_name='estimatelineitem',
            name='source_template',
        ),
    ]
