# Generated by Django 5.2.6 on 2026-06-28 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0033_remove_serviceitem_default_billable_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatelineitem',
            name='projection_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Per-source snapshot of the atom billing fields (description, qty, price, accounting_category) captured at projection/sync time, keyed "source_type:source_pk". Used to detect underlying-atom drift on re-projection. Empty for hand-added (sourceless) lines.'),
        ),
    ]
