# Generated by Django 5.2.6 on 2026-06-30 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0034_remove_changeorderlineitem_source_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatelineitemsource',
            name='source_type',
            field=models.CharField(choices=[('plan_task', 'PlanTask'), ('plan_material', 'PlanMaterial'), ('task', 'Task'), ('material', 'Material'), ('fee', 'Fee')], max_length=20),
        ),
    ]
