# Generated by Django 5.2.6 on 2026-06-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0035_alter_estimatelineitemsource_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatelineitemsource',
            name='source_type',
            field=models.CharField(choices=[('task', 'Task'), ('material', 'Material'), ('fee', 'Fee')], max_length=20),
        ),
    ]
