# Generated by Django 5.2.6 on 2026-06-30 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0036_alter_estimatelineitemsource_source_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estworksheet',
            name='job',
        ),
    ]
