# Generated by Django 5.2.6 on 2026-06-30 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0037_remove_estworksheet_job'),
        ('inventory', '0030_remove_material_source_plan_material_and_more'),
        ('jobs', '0053_remove_task_source_plan_task_alter_task_est_qty_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstWorksheet',
        ),
    ]
