# Generated by Django 5.2.6 on 2026-07-03 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0038_delete_estworksheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatelineitem',
            name='is_material',
            field=models.BooleanField(default=False, help_text='Marks a bare (no inventory_item, non-adjustment) freeform line as a material: at acceptance it crystallizes into a provisional Material (sell price only, no lot) instead of a Fee.'),
        ),
    ]
