# Generated by Django 5.2.6 on 2026-07-03 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0039_estimatelineitem_is_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatelineitem',
            name='service_item',
            field=models.ForeignKey(blank=True, help_text='Deferred service descriptor: crystallizes to a Task at acceptance.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='estimates.serviceitem'),
        ),
    ]
