# Generated by Django 5.2.6 on 2026-07-04 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0040_estimatelineitem_service_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeorderlineitem',
            name='is_material',
            field=models.BooleanField(default=False, help_text='Marks a bare (no inventory_item) freeform line as a material: at CO acceptance it crystallizes into a provisional Material (sell price only, no lot) instead of a Fee. Mirrors EstimateLineItem.is_material.'),
        ),
        migrations.AddField(
            model_name='changeorderlineitem',
            name='service_item',
            field=models.ForeignKey(blank=True, help_text='Deferred service descriptor: crystallizes to a Task at CO acceptance.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='estimates.serviceitem'),
        ),
        migrations.CreateModel(
            name='ChangeOrderLineItemSource',
            fields=[
                ('source_id', models.AutoField(primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('task', 'Task'), ('material', 'Material'), ('fee', 'Fee')], max_length=20)),
                ('source_pk', models.PositiveIntegerField()),
                ('change_order_line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='estimates.changeorderlineitem')),
            ],
            options={
                'db_table': 'co_li_sources',
                'unique_together': {('source_type', 'source_pk')},
            },
        ),
    ]
