# Generated by Django 5.2.6 on 2026-07-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0041_changeorderlineitem_is_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='qbo_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
