# Generated by Django 5.2.6 on 2026-07-22 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0042_serviceitem_qbo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changeorderlineitem',
            name='tax_rate_override',
        ),
        migrations.RemoveField(
            model_name='changeorderlineitem',
            name='taxable_override',
        ),
        migrations.RemoveField(
            model_name='estimatelineitem',
            name='tax_rate_override',
        ),
        migrations.RemoveField(
            model_name='estimatelineitem',
            name='taxable_override',
        ),
    ]
