# Generated by Django 5.2.6 on 2026-08-16 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0043_remove_changeorderlineitem_tax_rate_override_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeorderlineitem',
            name='is_comment',
            field=models.BooleanField(default=False, help_text='Informational line only — no charge, not linked to any task/atom.'),
        ),
        migrations.AddField(
            model_name='estimatelineitem',
            name='is_comment',
            field=models.BooleanField(default=False, help_text='Informational line only — no charge, not linked to any task/atom.'),
        ),
    ]
