# Generated by Django 5.2.6 on 2026-08-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0044_estimatelineitem_adjustment_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeorderlineitem',
            name='freeform_kind',
            field=models.CharField(blank=True, choices=[('work', 'Work'), ('material', 'Material'), ('fee', 'Fee / credit')], help_text='Set IFF this is a bare (no inventory_item, service_item) freeform line. "material" crystallizes at CO acceptance into a provisional Material (sell price only, no lot); anything else on a bare line (including unset) crystallizes into a Fee — CO acceptance does not yet branch on "work" (task-owned-money Phase 2, Task 3). Mirrors EstimateLineItem.freeform_kind.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='estimatelineitem',
            name='freeform_kind',
            field=models.CharField(blank=True, choices=[('work', 'Work'), ('material', 'Material'), ('fee', 'Fee / credit')], help_text='Set IFF this is a bare (no inventory_item, service_item, or adjustment_service) freeform line. "material" crystallizes at acceptance into a provisional Material (sell price only, no lot); anything else on a bare line (including unset) crystallizes into a Fee — acceptance does not yet branch on "work" (task-owned-money Phase 2, Task 3).', max_length=10, null=True),
        ),
        # NOTE: is_material's AlterField (help_text-only, no DB-level change) is
        # intentionally omitted here — it's a transitional field staged in
        # models.py only so this AddField migration and the 0047 RemoveField
        # migration can bracket the 0046 data migration; its help_text churn
        # isn't worth a migration operation for a field being deleted in two
        # migrations' time.
    ]
