# Generated by Django 5.2.6 on 2026-08-09 19:56
#
# Fee removal (spec docs/plans/2026-08-06-better-fees.md §10 phase 5):
# purge the legacy 'fee' source rows BEFORE the source_type choices narrow,
# so no row carries a value outside the new choice set. Reverse is a noop —
# fee data is unrecoverable by design (claimed lines already carry their
# stored values; the source rows were provenance-only and die with the
# Fee atom, dropped in jobs/0062_delete_fee which depends on this migration).

from django.db import migrations, models


def drop_fee_sources(apps, schema_editor):
    # Spec 2026-08-06-better-fees §10 phase 5: claimed lines already carry
    # their stored values; the fee source rows are provenance-only and die
    # with the Fee atom. Historical models have no custom delete(), so
    # QuerySet.delete() is correct here.
    for model_name in ('EstimateLineItemSource', 'ChangeOrderLineItemSource'):
        apps.get_model('estimates', model_name).objects.filter(source_type='fee').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0044_estimatelineitem_adjustment_percent'),
    ]

    operations = [
        migrations.RunPython(drop_fee_sources, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='changeorderlineitem',
            name='is_material',
            field=models.BooleanField(default=False, help_text='Marks a bare (no inventory_item) freeform line as a material: at CO acceptance it crystallizes into a provisional Material (sell price only, no lot); non-material bare lines stay document-only. Mirrors EstimateLineItem.is_material.'),
        ),
        migrations.AlterField(
            model_name='changeorderlineitemsource',
            name='source_type',
            field=models.CharField(choices=[('task', 'Task'), ('material', 'Material')], max_length=20),
        ),
        migrations.AlterField(
            model_name='estimatelineitem',
            name='is_material',
            field=models.BooleanField(default=False, help_text='Marks a bare (no inventory_item, non-adjustment) freeform line as a material: at acceptance it crystallizes into a provisional Material (sell price only, no lot); non-material bare lines stay document-only.'),
        ),
        migrations.AlterField(
            model_name='estimatelineitemsource',
            name='source_type',
            field=models.CharField(choices=[('task', 'Task'), ('material', 'Material')], max_length=20),
        ),
    ]
