# Generated by Django 5.2.6 on 2026-08-09 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_singular_units'),
        ('estimates', '0045_alter_changeorderlineitem_is_material_and_more'),
        ('jobs', '0062_delete_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeorderlineitem',
            name='adjustment_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Snapshot of adjustment_service's rate at creation time. compute_adjustment_amount reads this field, never the live scheme.", max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='changeorderlineitem',
            name='adjustment_service',
            field=models.ForeignKey(blank=True, help_text='Set when this line is a percentage adjustment (rush/discount).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='jobs.ratescheme'),
        ),
        migrations.AddField(
            model_name='changeorderlineitem',
            name='adjustment_target_categories',
            field=models.ManyToManyField(blank=True, help_text='Categories the adjustment applies to; empty = all non-adjustment lines.', related_name='+', to='core.accountingcategory'),
        ),
    ]
