# Generated by Django 5.2.6 on 2026-08-03 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0046_backfill_freeform_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changeorderlineitem',
            name='is_material',
        ),
        migrations.RemoveField(
            model_name='estimatelineitem',
            name='is_material',
        ),
    ]
