# Generated by Django 5.2.6 on 2026-08-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0047_remove_changeorderlineitem_is_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeorderlineitem',
            name='freeform_kind',
            field=models.CharField(blank=True, choices=[('work', 'Work'), ('material', 'Material'), ('fee', 'Fee / credit')], help_text='Set IFF this is a bare (no inventory_item, service_item) freeform line — required on an action=ADD line at entry (Task 4; not on REPLACE/REMOVE, which mirror the target atom or retire it). "material" crystallizes at CO acceptance into an established Material (reverse-markup placeholder cost); "work" into a flat Task; "fee" (or unset, for pre-migration rows) into a Fee. Mirrors EstimateLineItem.freeform_kind.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='estimatelineitem',
            name='freeform_kind',
            field=models.CharField(blank=True, choices=[('work', 'Work'), ('material', 'Material'), ('fee', 'Fee / credit')], help_text='Set IFF this is a bare (no inventory_item, service_item, or adjustment_service) freeform line — and, since Task 4, required on a bare line at ADD entry (no more silent default). "material" crystallizes at acceptance into an established Material (reverse-markup placeholder cost, QOH-0 lot); "work" into a flat Task (entered-qty, no RateScheme); "fee" (or unset, for pre-migration rows) into a Fee.', max_length=10, null=True),
        ),
    ]
