# Generated by Django 5.2.6 on 2026-08-16 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0047_backfill_descoped_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatelineitem',
            name='work_declined',
            field=models.BooleanField(default=False, help_text='The "no work needed" answer on the acceptance checklist: a job manager marks a plain hand line (no sources, not an adjustment, not a deposit line, no catalog identity) as declined instead of minting a task from it. Set-able only while the estimate is accepted; reversible (false = unanswered again).'),
        ),
    ]
