# Generated by Django 5.2.6 on 2026-09-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0048_estimatelineitem_work_declined'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeorderlineitem',
            name='per_unit',
            field=models.BooleanField(default=False, help_text="This line's claimed atoms describe ONE unit of qty (per-unit-lines spec §2), not the whole-job total. Mirrors EstimateLineItem.per_unit."),
        ),
        migrations.AddField(
            model_name='changeorderlineitemsource',
            name='per_unit_qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='changeorderlineitemsource',
            name='per_unit_worker_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estimatelineitem',
            name='per_unit',
            field=models.BooleanField(default=False, help_text="This line's claimed atoms describe ONE unit of qty (per-unit-lines spec §2), not the whole-job total. Atoms themselves always store whole-job totals; the per-unit snapshot lives on claim source rows."),
        ),
        migrations.AddField(
            model_name='estimatelineitemsource',
            name='per_unit_qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='estimatelineitemsource',
            name='per_unit_worker_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
