# Generated by Django 5.2.6 on 2026-08-04 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0048_alter_changeorderlineitem_freeform_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktemplate',
            name='is_product_structure',
            field=models.BooleanField(default=False),
        ),
    ]
