# Generated by Django 5.2.6 on 2026-08-16 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # Re-parented in the 2026-09-21 merge of origin/main: authored on main
        # against 0043; renumbered 0044->0050 onto this branch's chain.
        ('estimates', '0049_changeorderlineitem_per_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeorderlineitem',
            name='is_comment',
            field=models.BooleanField(default=False, help_text='Informational line only — no charge, not linked to any task/atom.'),
        ),
        migrations.AddField(
            model_name='estimatelineitem',
            name='is_comment',
            field=models.BooleanField(default=False, help_text='Informational line only — no charge, not linked to any task/atom.'),
        ),
    ]
