# Generated by Django 5.2.6 on 2026-10-06 21:05

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('vendor_invoice_number', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('received', 'Received'), ('partly_paid', 'Partly Paid'), ('paid_in_full', 'Paid in Full'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='draft', max_length=20)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('received_date', models.DateTimeField(blank=True, null=True)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('cancelled_date', models.DateTimeField(blank=True, null=True)),
                ('qbo_id', models.CharField(blank=True, max_length=50, null=True)),
                ('qbo_payment_status', models.CharField(blank=True, default='', max_length=50)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contacts.business')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contacts.contact')),
            ],
            options={
                'db_table': 'bills',
            },
        ),
        migrations.CreateModel(
            name='BillLineItem',
            fields=[
                ('line_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('line_number', models.PositiveIntegerField(blank=True, null=True)),
                ('qty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('units', models.CharField(default='none', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_comment', models.BooleanField(default=False, help_text='Informational line only — no charge, not linked to any task/atom.')),
                ('accounting_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to='core.accountingcategory')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchasing.bill')),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryitem')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='jobs.task')),
            ],
            options={
                'verbose_name': 'Bill Line Item',
                'verbose_name_plural': 'Bill Line Items',
                'db_table': 'bill_li',
            },
        ),
        migrations.CreateModel(
            name='BillPayment',
            fields=[
                ('qbo_id', models.CharField(blank=True, default='', max_length=50)),
                ('qbo_sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced to QBO'), ('sync_failed', 'QBO sync failed')], default='pending', max_length=20)),
                ('qbo_sync_error', models.TextField(blank=True, default='')),
                ('qbo_pending_op', models.CharField(blank=True, choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], default='', max_length=10)),
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField()),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('payment_account_id', models.CharField(blank=True, default='', max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('cleared_date', models.DateTimeField(blank=True, null=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchasing.bill')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_bill_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bill_payments',
                'ordering': ['payment_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('po_id', models.AutoField(primary_key=True, serialize=False)),
                ('po_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('partly_received', 'Partly Received'), ('received_in_full', 'Received in Full'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('requested_date', models.DateTimeField(blank=True, null=True)),
                ('issued_date', models.DateTimeField(blank=True, null=True)),
                ('received_date', models.DateTimeField(blank=True, null=True)),
                ('cancel_date', models.DateTimeField(blank=True, null=True)),
                ('bill_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vendor_invoice_ref', models.CharField(blank=True, default='', max_length=100)),
                ('reconciled', models.BooleanField(default=False)),
                ('reconciled_date', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contacts.business')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contacts.contact')),
            ],
            options={
                'db_table': 'pos',
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='purchasing.purchaseorder'),
        ),
        migrations.CreateModel(
            name='PurchaseOrderLineItem',
            fields=[
                ('line_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('line_number', models.PositiveIntegerField(blank=True, null=True)),
                ('qty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('units', models.CharField(default='none', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_comment', models.BooleanField(default=False, help_text='Informational line only — no charge, not linked to any task/atom.')),
                ('qty_received', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('received_date', models.DateTimeField(blank=True, null=True)),
                ('receipt_note', models.TextField(blank=True, default='')),
                ('qty_cancelled', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('invoice_only', models.BooleanField(default=False)),
                ('accounting_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to='core.accountingcategory')),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryitem')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchasing.purchaseorder')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_po_line_items', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='jobs.task')),
            ],
            options={
                'verbose_name': 'Purchase Order Line Item',
                'verbose_name_plural': 'Purchase Order Line Items',
                'db_table': 'po_li',
            },
        ),
    ]
