# Generated by Django 5.2.6 on 2026-03-29 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0002_rename_line_item_type_billlineitem_accounting_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='qbo_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='qbo_payment_status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
