# Generated by Django 5.2.6 on 2026-03-31 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0003_add_qbo_fields_to_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billlineitem',
            name='units',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='purchaseorderlineitem',
            name='units',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
