# Generated by Django 5.2.6 on 2026-04-08 06:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0005_purchaseorderlineitem_cancelled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderlineitem',
            name='cancelled',
        ),
        migrations.AddField(
            model_name='purchaseorderlineitem',
            name='qty_cancelled',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
