# Generated by Django 5.2.6 on 2026-04-18 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0006_remove_purchaseorderlineitem_cancelled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderlineitem',
            name='job',
        ),
    ]
