# Generated by Django 5.2.6 on 2026-05-14 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0007_remove_purchaseorderlineitem_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='bill_number',
        ),
    ]
