# Generated by Django 5.2.6 on 2026-02-01 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_line_item_type'),
        ('purchasing', '0008_update_lineitem_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='billlineitem',
            name='line_item_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to='core.lineitemtype'),
        ),
        migrations.AddField(
            model_name='billlineitem',
            name='tax_rate_override',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='billlineitem',
            name='taxable_override',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderlineitem',
            name='line_item_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to='core.lineitemtype'),
        ),
        migrations.AddField(
            model_name='purchaseorderlineitem',
            name='tax_rate_override',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderlineitem',
            name='taxable_override',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('received', 'Received'), ('partly_paid', 'Partly Paid'), ('paid_in_full', 'Paid in Full'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('partly_received', 'Partly Received'), ('received_in_full', 'Received in Full'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
