# Generated by Django 5.2.6 on 2026-06-16 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0008_remove_bill_bill_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billlineitem',
            old_name='price_list_item',
            new_name='inventory_item',
        ),
        migrations.RenameField(
            model_name='purchaseorderlineitem',
            old_name='price_list_item',
            new_name='inventory_item',
        ),
    ]
