# Generated by Django 5.2.6 on 2026-06-19 22:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0009_rename_price_list_item_billlineitem_inventory_item_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillPayment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField()),
                ('method', models.CharField(choices=[('check', 'Check'), ('credit_card', 'Credit Card'), ('ach', 'ACH'), ('cash', 'Cash'), ('other', 'Other')], max_length=20)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('qbo_payment_id', models.CharField(blank=True, default='', max_length=50)),
                ('cleared_date', models.DateTimeField(blank=True, null=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchasing.bill')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_bill_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bill_payments',
            },
        ),
    ]
