# Generated by Django 5.2.6 on 2026-02-12 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0009_add_tax_fields_to_line_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billlineitem',
            old_name='price_currency',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='purchaseorderlineitem',
            old_name='price_currency',
            new_name='price',
        ),
    ]
