# Generated by Django 5.2.6 on 2026-06-19 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0010_billpayment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billpayment',
            options={'ordering': ['payment_date']},
        ),
    ]
