# Generated by Django 5.2.6 on 2026-03-07 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0034_material_estimatelineitem_material'),
        ('purchasing', '0010_rename_price_currency_to_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='job',
        ),
        migrations.AddField(
            model_name='purchaseorderlineitem',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.job'),
        ),
    ]
