# Generated by Django 5.2.6 on 2026-03-05 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_copy_pricelist_to_inventory'),
        ('jobs', '0035_estimatelineitem_material'),
        ('purchasing', '0010_rename_price_currency_to_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderlineitem',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='purchaseorderlineitem',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.job'),
        ),
    ]
