# Generated by Django 5.2.6 on 2026-06-20 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0011_alter_billpayment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='purchasing.purchaseorder'),
        ),
    ]
