# Generated by Django 5.2.6 on 2026-03-05 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0012_copy_po_job_to_line_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='job',
        ),
    ]
