# Generated by Django 5.2.6 on 2026-06-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0012_alter_bill_purchase_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='vendor_invoice_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
