# Generated by Django 5.2.6 on 2026-06-22 04:10
# Hand-edited: corrected rename from qbo_payment_id->qbo_id (not payment_account_id),
# and added payment_account_id as a new AddField.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0013_alter_bill_vendor_invoice_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billpayment',
            old_name='qbo_payment_id',
            new_name='qbo_id',
        ),
        migrations.RemoveField(
            model_name='billpayment',
            name='method',
        ),
        migrations.AddField(
            model_name='billpayment',
            name='payment_account_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='billpayment',
            name='qbo_sync_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='billpayment',
            name='qbo_sync_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced to QBO'), ('sync_failed', 'QBO sync failed')], default='pending', max_length=20),
        ),
    ]
