# Generated by Django 5.2.6 on 2026-06-22 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0014_rename_qbo_payment_id_billpayment_payment_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billpayment',
            name='qbo_pending_op',
            field=models.CharField(blank=True, choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], default='', max_length=10),
        ),
    ]
