# Generated by Django 5.2.6 on 2026-07-05 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_alter_contact_email'),
        ('purchasing', '0015_billpayment_qbo_pending_op'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contacts.business'),
        ),
    ]
