# Generated by Django 5.2.6 on 2026-07-22 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0016_alter_purchaseorder_business'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billlineitem',
            name='tax_rate_override',
        ),
        migrations.RemoveField(
            model_name='billlineitem',
            name='taxable_override',
        ),
        migrations.RemoveField(
            model_name='purchaseorderlineitem',
            name='tax_rate_override',
        ),
        migrations.RemoveField(
            model_name='purchaseorderlineitem',
            name='taxable_override',
        ),
    ]
