# Generated by Django 5.2.6 on 2026-08-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0024_anchor_deliverables_latest'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='bill_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='reconciled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='reconciled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor_invoice_ref',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='purchaseorderlineitem',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderlineitem',
            name='invoice_only',
            field=models.BooleanField(default=False),
        ),
    ]
