# Generated by Django 5.2.6 on 2026-08-16 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0024_anchor_deliverables_latest'),
    ]

    operations = [
        migrations.AddField(
            model_name='billlineitem',
            name='is_comment',
            field=models.BooleanField(default=False, help_text='Informational line only — no charge, not linked to any task/atom.'),
        ),
        migrations.AddField(
            model_name='purchaseorderlineitem',
            name='is_comment',
            field=models.BooleanField(default=False, help_text='Informational line only — no charge, not linked to any task/atom.'),
        ),
    ]
