# Generated by Django 5.2.6 on 2026-10-06 21:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('business_id', models.AutoField(primary_key=True, serialize=False)),
                ('our_reference_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('business_name', models.CharField(max_length=255, unique=True)),
                ('business_address', models.TextField(blank=True)),
                ('business_phone', models.CharField(blank=True, max_length=50)),
                ('tax_exemption_number', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('tax_multiplier', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('qbo_customer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('qbo_vendor_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'businesses',
            },
        ),
        migrations.CreateModel(
            name='PaymentTerms',
            fields=[
                ('term_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('days', models.PositiveIntegerField(blank=True, null=True)),
                ('qbo_id', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'verbose_name': 'Payment Terms',
                'verbose_name_plural': 'Payment Terms',
                'db_table': 'terms',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_initial', models.CharField(blank=True, max_length=10)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('addr1', models.CharField(blank=True, max_length=255)),
                ('addr2', models.CharField(blank=True, max_length=255)),
                ('addr3', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('municipality', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country_code', models.CharField(blank=True, max_length=3)),
                ('mobile_number', models.CharField(blank=True, max_length=20)),
                ('work_number', models.CharField(blank=True, max_length=20)),
                ('home_number', models.CharField(blank=True, max_length=20)),
                ('qbo_customer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='contacts.business')),
                ('tags', models.ManyToManyField(blank=True, db_table='contact_tags', related_name='contacts', to='contacts.tag')),
            ],
            options={
                'db_table': 'contacts',
            },
        ),
        migrations.AddField(
            model_name='business',
            name='default_contact',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_for_business', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='business',
            name='terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.paymentterms'),
        ),
        migrations.AddField(
            model_name='business',
            name='tags',
            field=models.ManyToManyField(blank=True, db_table='business_tags', related_name='businesses', to='contacts.tag'),
        ),
    ]
