# Generated by Django 5.2.6 on 2026-03-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='qbo_customer_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='business',
            name='qbo_vendor_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
