# Generated by Django 5.2.6 on 2026-03-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_business_qbo_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='qbo_customer_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='qbo_vendor_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
