# Generated by Django 5.2.6 on 2026-03-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_business_qbo_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='qbo_customer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
