# Generated by Django 5.2.6 on 2026-05-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_contact_qbo_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='business',
            name='tags',
            field=models.ManyToManyField(blank=True, db_table='business_tags', related_name='businesses', to='contacts.tag'),
        ),
        migrations.AddField(
            model_name='contact',
            name='tags',
            field=models.ManyToManyField(blank=True, db_table='contact_tags', related_name='contacts', to='contacts.tag'),
        ),
    ]
