# Generated by Django 5.2.6 on 2026-05-29 04:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_tag_business_tags_contact_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
