# Generated by Django 5.2.6 on 2026-07-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_alter_business_business_name_alter_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='qbo_customer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='qbo_vendor_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
