# Generated by Django 5.2.6 on 2026-07-23 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_alter_business_qbo_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentterms',
            name='days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentterms',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='paymentterms',
            name='qbo_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
