# Generated by Django 5.2.6 on 2026-02-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0014_alter_business_default_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
