# Generated by Django 5.2.6 on 2026-02-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0015_alter_business_phone_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='tax_multiplier',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
