# Generated by Django 5.2.6 on 2026-10-06 21:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('core', '0001_initial'),
        ('estimates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blep',
            fields=[
                ('blep_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bleps',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_number', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('work_complete', 'Work Complete'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('on_hold', models.BooleanField(default=False)),
                ('hold_reason', models.TextField(blank=True, default='')),
                ('customer_po_number', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('accent_color', models.CharField(blank=True, help_text="Auto-assigned hex color (e.g. '#dc2626') used to identify the job in board and schedule views. Set on first save; persistent.", max_length=7, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contacts.contact')),
                ('project_manager', models.ForeignKey(blank=True, help_text='Informational owner of the job; no business-logic side effects.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
        migrations.CreateModel(
            name='RateScheme',
            fields=[
                ('rate_scheme_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('algorithm', models.CharField(choices=[('elapsed_time', 'Based on time worked'), ('entered_qty', 'Worker enters quantity'), ('percentage', 'Percentage of other lines'), ('flat_fee', 'Flat fee')], max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_label', models.CharField(max_length=50)),
                ('modifiers', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('accounting_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.accountingcategory')),
            ],
            options={
                'db_table': 'rate_schemes',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveIntegerField(blank=True, null=True)),
                ('est_worker_time', models.DurationField(blank=True, help_text='Estimated worker time for scheduling', null=True)),
                ('est_qty', models.DecimalField(blank=True, decimal_places=2, help_text="Estimated billable quantity in the task's own units (unit_label). Optional on Task.", max_digits=10, null=True)),
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('blocked', 'Blocked'), ('complete', 'Complete'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('blocked_reason', models.TextField(blank=True, default='')),
                ('worker_queue', models.PositiveIntegerField(blank=True, help_text="Position in assignee's work queue on the board", null=True)),
                ('qty_source', models.CharField(choices=[('elapsed_time', 'Timeslips'), ('entered_qty', 'Entered quantity')], default='entered_qty', max_length=20)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit_label', models.CharField(default='none', max_length=50)),
                ('active_modifiers', models.JSONField(blank=True, default=list)),
                ('actual_qty', models.DecimalField(blank=True, decimal_places=2, help_text='Worker-entered actual quantity for ENTERED_QTY schemes. Null for ELAPSED_TIME (qty derived from bleps).', max_digits=10, null=True)),
                ('accounting_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.accountingcategory')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('descoped_by', models.ForeignKey(blank=True, help_text="Accepted change order whose remove struck the agreement line this atom backed. Stamped at CO acceptance; drives the billing pool's 'descoped' badge.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='estimates.changeorder')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='jobs.job')),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='jobs.task')),
                ('service_item', models.ForeignKey(blank=True, help_text='Catalog identity: the ServiceItem this task was generated from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='estimates.serviceitem')),
                ('source_scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stamped_tasks', to='jobs.ratescheme')),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
        migrations.CreateModel(
            name='BlepChangeRequest',
            fields=[
                ('requested_start', models.DateTimeField()),
                ('requested_end', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=10)),
                ('has_known_conflict', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('blep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_requests', to='jobs.blep')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='jobs.task')),
            ],
            options={
                'db_table': 'blep_change_requests',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='blep',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.task'),
        ),
    ]
