# Generated by Django 5.2.6 on 2026-03-08 02:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('core', '0001_initial'),
        ('estimates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_number', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('customer_po_number', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contacts.contact')),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveIntegerField(blank=True, null=True)),
                ('units', models.CharField(blank=True, max_length=50)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('est_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mapping_strategy', models.CharField(choices=[('direct', 'Direct'), ('bundle', 'Bundle'), ('exclude', 'Exclude')], default='direct', max_length=20)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('est_worksheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estimates.estworksheet')),
                ('line_item_type', models.ForeignKey(blank=True, help_text='Type of line item this task produces when mapped directly', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.lineitemtype')),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='jobs.task')),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
        migrations.CreateModel(
            name='Blep',
            fields=[
                ('blep_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.task')),
            ],
            options={
                'db_table': 'bleps',
            },
        ),
        migrations.CreateModel(
            name='TaskBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('est_worksheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='estimates.estworksheet')),
                ('line_item_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.lineitemtype')),
                ('source_template_bundle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estimates.templatebundle')),
            ],
            options={
                'db_table': 'task_bundles',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='jobs.taskbundle'),
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('work_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('incomplete', 'Incomplete'), ('blocked', 'Blocked'), ('complete', 'Complete')], default='draft', max_length=20)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estimates.workordertemplate')),
            ],
            options={
                'db_table': 'workorders',
            },
        ),
        migrations.AddField(
            model_name='taskbundle',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='jobs.workorder'),
        ),
        migrations.AddField(
            model_name='task',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.workorder'),
        ),
    ]
