# Generated by Django 5.2.6 on 2026-03-16 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('blocked', 'Blocked'), ('complete', 'Complete')], default='incomplete', max_length=20),
        ),
    ]
