# Generated by Django 5.2.6 on 2026-03-30 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_rename_line_item_type_task_accounting_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='worker_queue',
            field=models.PositiveIntegerField(blank=True, help_text="Position in assignee's work queue on the board", null=True),
        ),
    ]
