# Generated by Django 5.2.6 on 2026-03-31 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_add_task_worker_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='units',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
