# Generated by Django 5.2.6 on 2026-04-06 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_task_split_data_move'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planbundle',
            name='description',
        ),
    ]
