# Generated by Django 5.2.6 on 2026-04-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_remove_planbundle_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='blocked_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
