# Generated by Django 5.2.6 on 2026-04-13 01:51

import django.db.models.deletion
from django.db import migrations, models


def backfill_task_job(apps, schema_editor):
    """Copy task.work_order.job_id into task.job_id for all existing tasks."""
    Task = apps.get_model('jobs', 'Task')
    WorkOrder = apps.get_model('jobs', 'WorkOrder')
    for task in Task.objects.all():
        if task.work_order_id is not None:
            wo = WorkOrder.objects.get(pk=task.work_order_id)
            task.job_id = wo.job_id
            task.save(update_fields=['job_id'])


def noop_reverse(apps, schema_editor):
    """Reverse migration is not supported; WorkOrder data cannot be reconstructed."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0009_rename_workordertemplate_worktemplate_and_more'),
        ('jobs', '0011_task_blocked_reason'),
    ]

    operations = [
        # 1. Add Job.template FK (unrelated to Task changes)
        migrations.AddField(
            model_name='job',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estimates.worktemplate'),
        ),
        # 2. Add Job.status choice for 'work_complete'
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('work_complete', 'Work Complete'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        # 3. Add Task.job as nullable so we can backfill
        migrations.AddField(
            model_name='task',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='jobs.job'),
        ),
        # 4. Copy task.work_order.job_id into task.job_id
        migrations.RunPython(backfill_task_job, noop_reverse),
        # 5. Make Task.job non-nullable now that data is backfilled
        migrations.AlterField(
            model_name='task',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='jobs.job'),
        ),
        # 6. Remove Task.work_order FK
        migrations.RemoveField(
            model_name='task',
            name='work_order',
        ),
        # 7. Delete the WorkOrder model
        migrations.DeleteModel(
            name='WorkOrder',
        ),
    ]
