# Generated by Django 5.2.6 on 2026-04-17 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_retire_can_approve_expenses'),
        ('jobs', '0012_remove_task_work_order_job_template_task_job_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateScheme',
            fields=[
                ('rate_scheme_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('algorithm', models.CharField(choices=[('elapsed_time', 'Based on time worked'), ('entered_qty', 'Worker enters quantity'), ('flat_fee', 'Fixed charge')], max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_label', models.CharField(max_length=50)),
                ('minimum_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('modifiers', models.JSONField(blank=True, default=list)),
                ('accounting_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.accountingcategory')),
            ],
            options={
                'db_table': 'rate_schemes',
            },
        ),
    ]
