# Generated by Django 5.2.6 on 2026-04-17 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_ratescheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanCharge',
            fields=[
                ('plan_charge_id', models.AutoField(primary_key=True, serialize=False)),
                ('active_modifiers', models.JSONField(blank=True, default=list)),
                ('estimated_billable_qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan_task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='charge', to='jobs.plantask')),
                ('rate_scheme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.ratescheme')),
            ],
            options={
                'db_table': 'plan_charges',
            },
        ),
        migrations.CreateModel(
            name='TaskCharge',
            fields=[
                ('task_charge_id', models.AutoField(primary_key=True, serialize=False)),
                ('active_modifiers', models.JSONField(blank=True, default=list)),
                ('actuals', models.JSONField(blank=True, default=dict)),
                ('rate_scheme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.ratescheme')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='charge', to='jobs.task')),
            ],
            options={
                'db_table': 'task_charges',
            },
        ),
    ]
