# Generated by Django 5.2.6 on 2026-04-17 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0009_rename_workordertemplate_worktemplate_and_more'),
        ('jobs', '0014_taskcharge_plancharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantask',
            name='est_worker_time',
            field=models.DurationField(blank=True, help_text='Estimated worker time for scheduling', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='est_worker_time',
            field=models.DurationField(blank=True, help_text='Estimated worker time for scheduling', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='source_template',
            field=models.ForeignKey(blank=True, help_text='TaskTemplate this task was created from', null=True, on_delete=django.db.models.deletion.SET_NULL, to='estimates.tasktemplate'),
        ),
    ]
