# Generated by Django 5.2.6 on 2026-04-20 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_task_source_plan_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantask',
            name='bundle',
        ),
        migrations.RemoveField(
            model_name='plantask',
            name='mapping_strategy',
        ),
        migrations.DeleteModel(
            name='PlanBundle',
        ),
    ]
