# Generated by Django 5.2.6 on 2026-05-01 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_drop_plan_bundle_and_mapping_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantask',
            name='active_modifiers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='plantask',
            name='estimated_billable_qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='plantask',
            name='rate_scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='jobs.ratescheme'),
        ),
    ]
