# Generated by Django 5.2.6 on 2026-02-01 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_line_item_type'),
        ('jobs', '0019_alter_blep_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatelineitem',
            name='line_item_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to='core.lineitemtype'),
        ),
        migrations.AddField(
            model_name='estimatelineitem',
            name='tax_rate_override',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='estimatelineitem',
            name='taxable_override',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
