# Generated by Django 5.2.6 on 2026-02-01 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_line_item_type'),
        ('jobs', '0020_add_tax_fields_to_line_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmapping',
            name='output_line_item_type',
            field=models.ForeignKey(blank=True, help_text='LineItemType to assign when tasks with this mapping become line items', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.lineitemtype'),
        ),
    ]
