# Generated by Django 5.2.6 on 2026-05-02 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_copy_plan_charge_to_plan_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='source_plan_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carried_task_new', to='jobs.plantask'),
        ),
    ]
