# Generated by Django 5.2.6 on 2026-02-03 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_lineitemtype_default_units'),
        ('jobs', '0021_add_line_item_type_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbundlingrule',
            name='output_line_item_type',
            field=models.ForeignKey(blank=True, help_text='LineItemType to assign to bundled line items. Overrides component task mappings if set.', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.lineitemtype'),
        ),
    ]
