# Generated by Django 5.2.6 on 2026-02-03 06:36
# Manually modified to preserve data during model rename

import django.db.models.deletion
from django.db import migrations, models


def convert_strategy_values(apps, schema_editor):
    """Convert bundle_to_product and bundle_to_service to bundle."""
    TaskMapping = apps.get_model('jobs', 'TaskMapping')
    TaskMapping.objects.filter(mapping_strategy='bundle_to_product').update(mapping_strategy='bundle')
    TaskMapping.objects.filter(mapping_strategy='bundle_to_service').update(mapping_strategy='bundle')


def reverse_strategy_values(apps, schema_editor):
    """Reverse the strategy conversion - default to bundle_to_product for safety."""
    TaskMapping = apps.get_model('jobs', 'TaskMapping')
    TaskMapping.objects.filter(mapping_strategy='bundle').update(mapping_strategy='bundle_to_product')


def update_template_placeholders(apps, schema_editor):
    """Update {product_identifier} to {bundle_identifier} in line_item_template."""
    BundlingRule = apps.get_model('jobs', 'BundlingRule')
    for rule in BundlingRule.objects.filter(line_item_template__contains='{product_identifier}'):
        rule.line_item_template = rule.line_item_template.replace('{product_identifier}', '{bundle_identifier}')
        rule.save()


def reverse_template_placeholders(apps, schema_editor):
    """Reverse: Update {bundle_identifier} back to {product_identifier}."""
    BundlingRule = apps.get_model('jobs', 'BundlingRule')
    for rule in BundlingRule.objects.filter(line_item_template__contains='{bundle_identifier}'):
        rule.line_item_template = rule.line_item_template.replace('{bundle_identifier}', '{product_identifier}')
        rule.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_lineitemtype_default_units'),
        ('jobs', '0022_add_output_line_item_type_to_bundling_rule'),
    ]

    operations = [
        # 1. Rename TaskInstanceMapping.product_identifier to bundle_identifier
        migrations.RenameField(
            model_name='taskinstancemapping',
            old_name='product_identifier',
            new_name='bundle_identifier',
        ),

        # 2. Rename ProductBundlingRule to BundlingRule (preserves data)
        migrations.RenameModel(
            old_name='ProductBundlingRule',
            new_name='BundlingRule',
        ),

        # 3. Add new fields to BundlingRule
        migrations.AddField(
            model_name='bundlingrule',
            name='default_units',
            field=models.CharField(
                choices=[('each', 'Each (quantity = 1 per bundle)'), ('hours', 'Hours (quantity = sum of task hours)')],
                default='each',
                max_length=20
            ),
        ),
        migrations.AddField(
            model_name='bundlingrule',
            name='description_template',
            field=models.TextField(
                blank=True,
                help_text='Template for line item description. Use {tasks_list} for bullet list of task names.'
            ),
        ),

        # 4. Convert existing strategy values before changing choices
        migrations.RunPython(convert_strategy_values, reverse_strategy_values),

        # 5. Update template placeholders from {product_identifier} to {bundle_identifier}
        migrations.RunPython(update_template_placeholders, reverse_template_placeholders),

        # 6. Update TaskMapping.mapping_strategy choices
        migrations.AlterField(
            model_name='taskmapping',
            name='mapping_strategy',
            field=models.CharField(
                choices=[
                    ('direct', 'Direct - One task to one line item'),
                    ('bundle', 'Bundle into single line item'),
                    ('exclude', 'Internal only - exclude from estimate')
                ],
                default='direct',
                max_length=30
            ),
        ),
    ]
