# Generated by Django 5.2.6 on 2026-05-02 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0022_backfill_task_source_plan_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='source_plan_task',
            field=models.OneToOneField(blank=True, help_text='PlanTask this task was carried over from (carry-over idempotency; replaces source_plan_charge in Task 12)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carried_task_new', to='jobs.plantask'),
        ),
    ]
