# Generated by Django 5.2.6 on 2026-02-04 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0023_consolidate_bundling_strategies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundlingrule',
            name='description_template',
        ),
        migrations.RemoveField(
            model_name='bundlingrule',
            name='line_item_template',
        ),
    ]
