# Generated by Django 5.2.6 on 2026-05-02 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0024_drop_plan_charge_and_source_plan_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantask',
            name='est_qty',
        ),
        migrations.RemoveField(
            model_name='plantask',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='plantask',
            name='units',
        ),
    ]
