# Generated by Django 5.2.6 on 2026-02-08 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0024_remove_template_fields_from_bundling_rule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskinstancemapping',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskmapping',
            name='output_line_item_type',
        ),
        migrations.RemoveField(
            model_name='tasktemplate',
            name='task_mapping',
        ),
        migrations.RemoveField(
            model_name='workordertemplate',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='workordertemplate',
            name='template_type',
        ),
        migrations.DeleteModel(
            name='BundlingRule',
        ),
        migrations.DeleteModel(
            name='TaskInstanceMapping',
        ),
        migrations.DeleteModel(
            name='TaskMapping',
        ),
    ]
