# Generated by Django 5.2.6 on 2026-05-03 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0025_remove_plantask_est_qty_remove_plantask_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratescheme',
            name='replaced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ratescheme',
            name='replaced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replaces', to='jobs.ratescheme'),
        ),
    ]
