# Generated by Django 5.2.6 on 2026-02-08 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_lineitemtype_default_units'),
        ('jobs', '0025_drop_old_templating_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktemplate',
            name='line_item_type',
            field=models.ForeignKey(blank=True, help_text='Type of line item this task produces when mapped directly', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.lineitemtype'),
        ),
    ]
