# Generated by Django 5.2.6 on 2026-02-08 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_lineitemtype_default_units'),
        ('jobs', '0026_add_line_item_type_to_task_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('line_item_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.lineitemtype')),
                ('work_order_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='jobs.workordertemplate')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'unique_together': {('work_order_template', 'name')},
            },
        ),
    ]
