# Generated by Django 5.2.6 on 2026-05-03 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0026_ratescheme_replaced_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantask',
            old_name='estimated_billable_qty',
            new_name='est_qty',
        ),
    ]
