# Generated by Django 5.2.6 on 2026-02-08 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0027_create_template_bundle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='templatetaskassociation',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='templatetaskassociation',
            name='bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associations', to='jobs.templatebundle'),
        ),
        migrations.AddField(
            model_name='templatetaskassociation',
            name='mapping_strategy',
            field=models.CharField(choices=[('direct', 'Direct - becomes its own line item'), ('bundle', 'Bundle - part of a bundled line item'), ('exclude', 'Exclude - internal only, not on estimate')], default='direct', max_length=20),
        ),
        migrations.AlterField(
            model_name='templatetaskassociation',
            name='est_qty',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
