# Generated by Django 5.2.6 on 2026-05-03 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_retire_can_approve_expenses'),
        ('jobs', '0027_plantask_rename_est_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratescheme',
            name='accounting_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.accountingcategory'),
        ),
    ]
