# Generated by Django 5.2.6 on 2026-05-03 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0028_ratescheme_ac_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantask',
            name='est_qty',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='plantask',
            name='rate_scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.ratescheme'),
        ),
    ]
