# Generated by Django 5.2.6 on 2026-02-11 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0028_add_mapping_to_association'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='line_number',
            new_name='sort_order',
        ),
    ]
