# Generated by Django 5.2.6 on 2026-05-04 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0029_planTask_billing_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='est_qty',
        ),
        migrations.RemoveField(
            model_name='task',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='task',
            name='units',
        ),
    ]
