# Generated by Django 5.2.6 on 2026-02-11 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_lineitemtype_default_units'),
        ('jobs', '0029_rename_task_line_number_to_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='mapping_strategy',
            field=models.CharField(choices=[('direct', 'Direct'), ('bundle', 'Bundle'), ('exclude', 'Exclude')], default='direct', max_length=20),
        ),
        migrations.CreateModel(
            name='TaskBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('est_worksheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='jobs.estworksheet')),
                ('line_item_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.lineitemtype')),
                ('source_template_bundle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.templatebundle')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='jobs.workorder')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='jobs.taskbundle'),
        ),
    ]
