# Generated by Django 5.2.6 on 2026-05-04 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0030_drop_task_legacy_billing_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantask',
            name='accounting_category',
        ),
        migrations.RemoveField(
            model_name='task',
            name='accounting_category',
        ),
    ]
