# Generated by Django 5.2.6 on 2026-02-12 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0030_add_taskbundle_and_task_mapping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estimatelineitem',
            old_name='price_currency',
            new_name='price',
        ),
    ]
