# Generated by Django 5.2.6 on 2026-05-04 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0031_drop_workitem_ac_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratescheme',
            name='minimum_charge',
        ),
    ]
