# Generated by Django 5.2.6 on 2026-05-07 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0032_remove_ratescheme_minimum_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='active_modifiers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='task',
            name='actual_qty',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Worker-entered actual quantity for ENTERED_QTY schemes. Null for ELAPSED_TIME (qty derived from bleps) and FLAT_FEE.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='est_qty',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Estimated billable quantity in the rate scheme's units. Required at the application layer on PlanTask; optional on Task.", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='rate_scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='jobs.ratescheme'),
        ),
        migrations.AlterField(
            model_name='plantask',
            name='est_qty',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Estimated billable quantity in the rate scheme's units. Required at the application layer on PlanTask; optional on Task.", max_digits=10, null=True),
        ),
    ]
