# Generated by Django 5.2.6 on 2026-02-18 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_lineitemtype_default_units'),
        ('jobs', '0032_task_add_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='line_item_type',
            field=models.ForeignKey(blank=True, help_text='Type of line item this task produces when mapped directly', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.lineitemtype'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='template',
        ),
    ]
