# Generated by Django 5.2.6 on 2026-03-07 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_emailrecord_tempemail'),
        ('jobs', '0034_material_estimatelineitem_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='line_item_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.lineitemtype'),
        ),
    ]
