# Generated by Django 5.2.6 on 2026-03-05 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0034_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatelineitem',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.material'),
        ),
    ]
