# Generated by Django 5.2.6 on 2026-05-07 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0035_phase_b_tighten_task_rate_scheme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskCharge',
        ),
    ]
