# Generated by Django 5.2.6 on 2026-05-13 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0036_phase_b_drop_taskcharge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='template',
        ),
    ]
