# Generated by Django 5.2.6 on 2026-05-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0037_remove_job_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='accent_color',
            field=models.CharField(blank=True, help_text="Auto-assigned hex color (e.g. '#dc2626') used to identify the job in board and schedule views. Set on first save; persistent.", max_length=7, null=True),
        ),
    ]
