# Generated by Django 5.2.6 on 2026-06-24 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0045_reframe_flat_fee_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprice',
            name='algorithm',
            field=models.CharField(choices=[('elapsed_time', 'Based on time worked'), ('entered_qty', 'Worker enters quantity'), ('flat_fee', 'Fixed charge'), ('percentage', 'Percentage of other lines')], max_length=20),
        ),
    ]
