# Generated by Django 5.2.6 on 2026-06-27 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0032_alter_estimatelineitem_source_template_and_more'),
        ('jobs', '0048_rename_serviceitem_to_ratescheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='source_template',
            field=models.ForeignKey(blank=True, help_text='ServiceItem this task was created from', null=True, on_delete=django.db.models.deletion.SET_NULL, to='estimates.serviceitem'),
        ),
    ]
