# Generated by Django 5.2.6 on 2026-06-28 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0049_alter_task_source_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='source_template',
        ),
    ]
