# Generated by Django 5.2.6 on 2026-06-30 05:56

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_expenseshistory'),
        ('jobs', '0050_remove_task_source_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('fee_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('unit_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('accounting_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.accountingcategory')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='jobs.job')),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee', to='jobs.task')),
            ],
            options={
                'db_table': 'fees',
            },
        ),
    ]
