# Generated by Django 5.2.6 on 2026-06-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0051_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratescheme',
            name='algorithm',
            field=models.CharField(choices=[('elapsed_time', 'Based on time worked'), ('entered_qty', 'Worker enters quantity'), ('percentage', 'Percentage of other lines')], max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='actual_qty',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Worker-entered actual quantity for ENTERED_QTY schemes. Null for ELAPSED_TIME (qty derived from bleps).', max_digits=10, null=True),
        ),
    ]
