# Generated by Django 5.2.6 on 2026-06-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_remove_material_source_plan_material_and_more'),
        ('jobs', '0052_alter_ratescheme_algorithm_alter_task_actual_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='source_plan_task',
        ),
        migrations.AlterField(
            model_name='task',
            name='est_qty',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Estimated billable quantity in the rate scheme's units. Optional on Task.", max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='PlanTask',
        ),
    ]
