# Generated by Django 5.2.6 on 2026-07-06 02:35

from django.db import migrations, models


def held_status_to_flag(apps, schema_editor):
    """Best-effort mapping for pre-flag rows: an 'on_hold' STATUS becomes
    approved + the flag. (Held-from-in_progress can't be distinguished after
    the fact; dev data is regenerable from nealsdata.)"""
    Job = apps.get_model('jobs', 'Job')
    for job in Job.objects.filter(status='on_hold'):
        job.status = 'approved'
        job.on_hold = True
        job.save(update_fields=['status', 'on_hold'])


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0053_remove_task_source_plan_task_alter_task_est_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='on_hold',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(held_status_to_flag, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('work_complete', 'Work Complete'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
