# Generated by Django 5.2.6 on 2026-07-22 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0042_serviceitem_qbo_id'),
        ('jobs', '0054_job_on_hold_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='service_item',
            field=models.ForeignKey(blank=True, help_text='Catalog identity: the ServiceItem this task was generated from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='estimates.serviceitem'),
        ),
    ]
