# Generated by Django 5.2.6 on 2026-08-03 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_singular_units'),
        ('jobs', '0055_task_service_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='accounting_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.accountingcategory'),
        ),
        migrations.AddField(
            model_name='task',
            name='qty_source',
            field=models.CharField(choices=[('elapsed_time', 'Timeslips'), ('entered_qty', 'Entered quantity')], default='entered_qty', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='unit_label',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
