# Generated by Django 5.2.6 on 2026-08-03 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0058_backfill_task_money'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratescheme',
            name='replaced_at',
        ),
        migrations.RemoveField(
            model_name='ratescheme',
            name='replaced_by',
        ),
        migrations.AddField(
            model_name='ratescheme',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
