# Generated by Django 5.2.6 on 2026-08-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0059_ratescheme_slim_supersession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='est_qty',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Estimated billable quantity in the task's own units (unit_label). Optional on Task.", max_digits=10, null=True),
        ),
    ]
