# Generated by Django 5.2.6 on 2026-08-03 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0060_alter_task_est_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='task',
        ),
    ]
