# Generated by Django 5.2.6 on 2026-08-04 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0061_fee_drop_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='qty_scales_with_parent',
            field=models.BooleanField(default=True, help_text="Subtask only: when true, this task's raw est_qty/est_worker_time are PER-UNIT and multiply by the parent's est_qty to get the expected total (Task.expected_qty() / expected_worker_time()). When false, the raw values are already a per-batch total (multiplier 1). Inert on a top-level task (no parent)."),
        ),
    ]
