# Generated by Django 5.2.6 on 2026-08-09 19:56
#
# Fee removal (spec docs/plans/2026-08-06-better-fees.md §10 phase 5):
# drop the Fee model. Depends on the estimates/invoicing source-row purges
# so every 'fee' source row is gone before the fees table drops.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0061_flatten_subtasks'),
        ('estimates', '0045_alter_changeorderlineitem_is_material_and_more'),
        ('invoicing', '0024_alter_invoicelineitemsource_source_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fee',
        ),
    ]
