# Generated by Django 5.2.6 on 2026-08-17 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0063_task_descoped_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratescheme',
            name='algorithm',
            field=models.CharField(choices=[('elapsed_time', 'Based on time worked'), ('entered_qty', 'Worker enters quantity'), ('percentage', 'Percentage of other lines'), ('flat_fee', 'Flat fee')], max_length=20),
        ),
    ]
