# Generated by Django 5.2.6 on 2026-10-06 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QBOConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realm_id', models.CharField(max_length=50)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('access_token_expires_at', models.DateTimeField()),
                ('refresh_token_expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('connected_at', models.DateTimeField()),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'qbo_connection',
            },
        ),
        migrations.CreateModel(
            name='QBOSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.IntegerField()),
                ('qbo_entity_type', models.CharField(max_length=50)),
                ('qbo_entity_id', models.CharField(blank=True, max_length=50)),
                ('action', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'qbo_sync_log',
                'ordering': ['-synced_at'],
            },
        ),
    ]
