# Generated by Django 5.2.6 on 2026-10-06 21:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('qty_ordered', models.DecimalField(decimal_places=2, max_digits=10)),
                ('units', models.CharField(max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'deliverables',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='DeliverableSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('qty_ordered', models.DecimalField(decimal_places=2, max_digits=10)),
                ('units', models.CharField(max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'deliverable_snapshots',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('prepared', 'Prepared'), ('picked_up', 'Picked up')], default='prepared', max_length=20)),
                ('prepared_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('picked_up_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'shipments',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'shipment_items',
                'ordering': ['deliverable__sort_order'],
            },
        ),
    ]
