# Generated by Django 5.2.6 on 2026-05-14 07:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0037_remove_job_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('qty_ordered', models.DecimalField(decimal_places=2, max_digits=10)),
                ('units', models.CharField(max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='jobs.job')),
            ],
            options={
                'db_table': 'deliverables',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('prepared', 'Prepared'), ('picked_up', 'Picked up')], default='prepared', max_length=20)),
                ('prepared_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('picked_up_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='jobs.job')),
            ],
            options={
                'db_table': 'shipments',
                'ordering': ['sequence'],
                'unique_together': {('job', 'sequence')},
            },
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deliverable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_items', to='deliverables.deliverable')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='deliverables.shipment')),
            ],
            options={
                'db_table': 'shipment_items',
                'ordering': ['deliverable__sort_order'],
                'unique_together': {('shipment', 'deliverable')},
            },
        ),
    ]
