# Generated by Django 5.2.6 on 2026-10-06 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliverables', '0001_initial'),
        ('estimates', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverable',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='source_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliverables', to='estimates.estimatelineitem'),
        ),
        migrations.AddField(
            model_name='deliverablesnapshot',
            name='change_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliverable_snapshots', to='estimates.changeorder'),
        ),
        migrations.AddField(
            model_name='deliverablesnapshot',
            name='estimate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliverable_snapshots', to='estimates.estimate'),
        ),
        migrations.AddField(
            model_name='deliverablesnapshot',
            name='source_deliverable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='deliverables.deliverable'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='deliverable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_items', to='deliverables.deliverable'),
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='deliverables.shipment'),
        ),
        migrations.AlterUniqueTogether(
            name='shipment',
            unique_together={('job', 'sequence')},
        ),
        migrations.AlterUniqueTogether(
            name='shipmentitem',
            unique_together={('shipment', 'deliverable')},
        ),
    ]
