# Generated by Django 5.2.6 on 2026-05-26 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0001_initial'),
        ('estimates', '0021_changeorder_changeorderlineitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverableSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('qty_ordered', models.DecimalField(decimal_places=2, max_digits=10)),
                ('units', models.CharField(max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('change_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliverable_snapshots', to='estimates.changeorder')),
                ('estimate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliverable_snapshots', to='estimates.estimate')),
                ('source_deliverable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='deliverables.deliverable')),
            ],
            options={
                'db_table': 'deliverable_snapshots',
                'ordering': ['sort_order'],
            },
        ),
    ]
