# Generated by Django 5.2.6 on 2026-08-04 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0002_deliverablesnapshot'),
        ('jobs', '0062_task_qty_scales_with_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverable',
            name='source_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourced_deliverables', to='jobs.task'),
        ),
    ]
