# Generated by Django 5.2.6 on 2026-08-13 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0002_deliverablesnapshot'),
        ('estimates', '0047_backfill_descoped_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverable',
            name='source_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliverables', to='estimates.estimatelineitem'),
        ),
    ]
