# Generated by Django 5.2.6 on 2026-10-06 21:05

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('taxable', models.BooleanField(default=True)),
                ('default_description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deposit', models.BooleanField(default=False)),
                ('qbo_item_id', models.CharField(blank=True, default='', max_length=50)),
                ('qbo_expense_account_id', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'accounting categories',
                'db_table': 'accounting_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AppState',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'App State',
                'verbose_name_plural': 'App State',
                'db_table': 'appstate',
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configurations',
                'db_table': 'config',
            },
        ),
        migrations.CreateModel(
            name='EmailRecord',
            fields=[
                ('email_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('message_id', models.CharField(db_index=True, help_text='RFC 2822 Message-ID header', max_length=255, unique=True)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], default='inbound', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_send_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Email Record',
                'verbose_name_plural': 'Email Records',
                'db_table': 'email_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpensesHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('audit', 'Audit'), ('action', 'Action'), ('note', 'Note')], max_length=10)),
                ('object_type', models.CharField(max_length=50)),
                ('object_id', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('text', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'expenses_history',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='InventoryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('audit', 'Audit'), ('action', 'Action'), ('note', 'Note')], max_length=10)),
                ('object_type', models.CharField(max_length=50)),
                ('object_id', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('text', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'inventory_history',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='JobHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('audit', 'Audit'), ('action', 'Action'), ('note', 'Note')], max_length=10)),
                ('object_type', models.CharField(max_length=50)),
                ('object_id', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('text', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'job_history',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LoginEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'db_table': 'login_events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PurchasingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('audit', 'Audit'), ('action', 'Action'), ('note', 'Note')], max_length=10)),
                ('object_type', models.CharField(max_length=50)),
                ('object_id', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('text', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'purchasing_history',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledProcessRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.CharField(db_index=True, max_length=100)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('ok', 'OK'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='ok', max_length=10)),
                ('summary', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'scheduled_process_run',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('shift_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shifts',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ShiftChangeRequest',
            fields=[
                ('requested_start', models.DateTimeField()),
                ('requested_end', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=10)),
                ('has_known_conflict', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'shift_change_requests',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TempEmail',
            fields=[
                ('temp_email_id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(db_index=True, help_text='IMAP UID for fetching message content', max_length=100)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('from_email', models.EmailField(max_length=254)),
                ('to_email', models.TextField(help_text='Comma-separated email addresses')),
                ('cc_email', models.TextField(blank=True, help_text='Comma-separated email addresses')),
                ('bcc_email', models.TextField(blank=True, default='', help_text='Comma-separated email addresses')),
                ('date_sent', models.DateTimeField()),
                ('in_reply_to', models.CharField(blank=True, default='', max_length=255)),
                ('references', models.TextField(blank=True, default='')),
                ('text_body', models.TextField(blank=True, default='')),
                ('html_body', models.TextField(blank=True, default='')),
                ('attachments_metadata', models.JSONField(blank=True, default=list)),
                ('is_read', models.BooleanField(default=False)),
                ('is_starred', models.BooleanField(default=False)),
                ('has_attachments', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Temporary Email',
                'verbose_name_plural': 'Temporary Emails',
                'db_table': 'temp_email',
                'ordering': ['-date_sent'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('schedule_envelope', models.JSONField(blank=True, help_text='Per-worker weekly working pattern for the schedule (canonical {"mon": [["08:00", "17:00"]], …} shape). NULL means the worker uses the shop default (the schedule_week_envelope Configuration key). Validated by apps.schedule.calendar_arithmetic.', null=True)),
                ('contact', models.OneToOneField(blank=True, help_text='Associated contact record for this user', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.contact')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'auth_user',
                'permissions': [('can_manage_jobs', 'Can manage jobs, estimates, worksheets, work orders, tasks, contacts'), ('can_manage_financials', 'Can manage invoices, POs, bills, price list'), ('can_manage_time', "Can edit/delete anyone's time entries"), ('can_manage_config', 'Can manage settings, templates, user admin')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CrmHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('audit', 'Audit'), ('action', 'Action'), ('note', 'Note')], max_length=10)),
                ('object_type', models.CharField(max_length=50)),
                ('object_id', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('text', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crm_history',
                'ordering': ['-timestamp'],
            },
        ),
    ]
