# Generated by Django 5.2.6 on 2026-10-06 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('jobs', '0001_initial'),
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailrecord',
            name='bill',
            field=models.ForeignKey(blank=True, help_text='Associated bill for this email', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_records', to='purchasing.bill'),
        ),
        migrations.AddField(
            model_name='emailrecord',
            name='job',
            field=models.ForeignKey(blank=True, help_text='Associated job for this email', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_records', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='emailrecord',
            name='purchase_order',
            field=models.ForeignKey(blank=True, help_text='Associated purchase order for this email', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_records', to='purchasing.purchaseorder'),
        ),
        migrations.AddField(
            model_name='expenseshistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loginevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasinghistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shift',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shiftchangerequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shiftchangerequest',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shiftchangerequest',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_requests', to='core.shift'),
        ),
        migrations.AddField(
            model_name='tempemail',
            name='email_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='temp_data', to='core.emailrecord'),
        ),
        migrations.AddIndex(
            model_name='loginevent',
            index=models.Index(fields=['user', '-timestamp'], name='login_event_user_id_b4867a_idx'),
        ),
        migrations.AddIndex(
            model_name='tempemail',
            index=models.Index(fields=['-date_sent'], name='temp_email_date_se_5026a4_idx'),
        ),
        migrations.AddIndex(
            model_name='tempemail',
            index=models.Index(fields=['uid'], name='temp_email_uid_6bd42f_idx'),
        ),
    ]
