# Generated by Django 5.2.6 on 2026-03-08 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailrecord',
            name='job',
            field=models.ForeignKey(blank=True, help_text='Associated job for this email', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_records', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='tempemail',
            name='email_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='temp_data', to='core.emailrecord'),
        ),
        migrations.AddIndex(
            model_name='tempemail',
            index=models.Index(fields=['-date_sent'], name='temp_email_date_se_5026a4_idx'),
        ),
        migrations.AddIndex(
            model_name='tempemail',
            index=models.Index(fields=['uid'], name='temp_email_uid_6bd42f_idx'),
        ),
    ]
