# Generated by Django 5.2.6 on 2026-02-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_configuration_estimate_number_sequence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('taxable', models.BooleanField(default=True)),
                ('default_units', models.CharField(blank=True, max_length=50)),
                ('default_description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
