# Generated by Django 5.2.6 on 2026-03-21 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_historyentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_manage_jobs', 'Can manage jobs, estimates, worksheets, work orders, tasks'), ('can_view_jobs', 'Read-only access to all jobs and related documents'), ('can_manage_invoicing', 'Can manage invoices, price list, send/payment'), ('can_manage_purchasing', 'Can manage POs, bills, send/receive'), ('can_manage_time', "Can edit/delete anyone's time entries"), ('can_approve_expenses', 'Can approve/reject expenses over threshold'), ('can_manage_config', 'Can manage settings, templates, user admin')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
