# Generated by Django 5.2.6 on 2026-02-01 05:04

from django.db import migrations


def create_default_line_item_types(apps, schema_editor):
    """Create default LineItemTypes for common item categories."""
    LineItemType = apps.get_model('core', 'LineItemType')

    default_types = [
        {
            'code': 'SVC',
            'name': 'Service',
            'taxable': False,  # Services are typically non-taxable
            'default_units': 'hours',
            'default_description': '',
            'is_active': True
        },
        {
            'code': 'MAT',
            'name': 'Material',
            'taxable': True,
            'default_units': 'each',
            'default_description': '',
            'is_active': True
        },
        {
            'code': 'PRD',
            'name': 'Product',
            'taxable': True,
            'default_units': 'each',
            'default_description': '',
            'is_active': True
        },
        {
            'code': 'FRT',
            'name': 'Freight',
            'taxable': True,  # Taxability varies by jurisdiction, default to taxable
            'default_units': '',
            'default_description': '',
            'is_active': True
        },
        {
            'code': 'MISC',
            'name': 'Miscellaneous',
            'taxable': True,
            'default_units': 'each',
            'default_description': '',
            'is_active': True
        },
    ]

    for type_data in default_types:
        LineItemType.objects.get_or_create(
            code=type_data['code'],
            defaults=type_data
        )


def remove_default_line_item_types(apps, schema_editor):
    """Remove default LineItemTypes (for migration reversal)."""
    LineItemType = apps.get_model('core', 'LineItemType')
    default_codes = ['SVC', 'MAT', 'PRD', 'FRT', 'MISC']
    LineItemType.objects.filter(code__in=default_codes).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_line_item_type'),
    ]

    operations = [
        migrations.RunPython(
            create_default_line_item_types,
            remove_default_line_item_types
        ),
    ]
