# Generated by Django 5.2.6 on 2026-03-28 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_create_default_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_view_financials', 'Read-only access to invoices, POs, bills'), ('can_manage_jobs', 'Can manage jobs, estimates, worksheets, work orders, tasks, contacts'), ('can_manage_financials', 'Can manage invoices, POs, bills, price list'), ('can_manage_time', "Can edit/delete anyone's time entries"), ('can_approve_expenses', 'Can approve/reject expenses over threshold'), ('can_manage_config', 'Can manage settings, templates, user admin')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
