# Generated by Django 5.2.6 on 2026-03-29 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cleanup_old_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitemtype',
            name='qbo_expense_account_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='lineitemtype',
            name='qbo_item_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
