# Generated by Django 5.2.6 on 2026-04-05 15:22

from django.db import migrations


DROPPED_ATOM = 'can_view_financials'


def cleanup_dropped_atom(apps, schema_editor):
    """Remove the can_view_financials Permission row and any stale
    user_permissions / group_permissions references to it.

    The model-level change (AlterModelOptions) above updates the
    declared permissions tuple; Django's post_migrate signal does
    NOT delete Permission rows for removed atoms, so we do it here.
    """
    Permission = apps.get_model('auth', 'Permission')
    perms = Permission.objects.filter(
        codename=DROPPED_ATOM, content_type__app_label='core',
    )
    # Group-permission M2M entries cascade when Permission is deleted.
    # user_permissions M2M entries also cascade.
    perms.delete()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_lineitemtype_to_accountingcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_manage_jobs', 'Can manage jobs, estimates, worksheets, work orders, tasks, contacts'), ('can_manage_financials', 'Can manage invoices, POs, bills, price list'), ('can_manage_time', "Can edit/delete anyone's time entries"), ('can_approve_expenses', 'Can approve/reject expenses over threshold'), ('can_manage_config', 'Can manage settings, templates, user admin')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RunPython(cleanup_dropped_atom, noop),
    ]
