# Generated by Django 5.2.6 on 2026-05-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_retire_can_approve_expenses'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledProcessRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.CharField(db_index=True, max_length=100)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('ok', 'OK'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='ok', max_length=10)),
                ('summary', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'scheduled_process_run',
                'ordering': ['-started_at'],
            },
        ),
    ]
