# Generated by Django 5.2.6 on 2026-05-29 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_scheduledprocessrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempemail',
            name='attachments_metadata',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tempemail',
            name='html_body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tempemail',
            name='text_body',
            field=models.TextField(blank=True, default=''),
        ),
    ]
