# Generated by Django 5.2.6 on 2026-05-29 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_tempemail_body_and_attachment_cache'),
        ('purchasing', '0008_remove_bill_bill_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailrecord',
            name='bill',
            field=models.ForeignKey(blank=True, help_text='Associated bill for this email', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_records', to='purchasing.bill'),
        ),
        migrations.AddField(
            model_name='emailrecord',
            name='purchase_order',
            field=models.ForeignKey(blank=True, help_text='Associated purchase order for this email', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_records', to='purchasing.purchaseorder'),
        ),
    ]
