# Generated by Django 5.2.6 on 2026-05-29 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_emailrecord_bill_emailrecord_purchase_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailrecord',
            name='direction',
            field=models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], default='inbound', max_length=10),
        ),
        migrations.AddField(
            model_name='emailrecord',
            name='last_send_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='emailrecord',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tempemail',
            name='bcc_email',
            field=models.TextField(blank=True, default='', help_text='Comma-separated email addresses'),
        ),
        migrations.AddField(
            model_name='tempemail',
            name='in_reply_to',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='tempemail',
            name='references',
            field=models.TextField(blank=True, default=''),
        ),
    ]
