# Generated by Django 5.2.6 on 2026-05-31 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_shiftchangerequest'),
        ('core', '0015_emailrecord_direction_emailrecord_last_send_error_and_more'),
    ]

    operations = [
    ]
