# Generated by Django 5.2.6 on 2026-06-06 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_merge_20260531_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppState',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'App State',
                'verbose_name_plural': 'App State',
                'db_table': 'appstate',
            },
        ),
    ]
