# Generated by Django 5.2.6 on 2026-06-10 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_crmhistory_jobhistory_purchasinghistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoryEntry',
        ),
    ]
