# Generated by Django 5.2.6 on 2026-07-06 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_anchor_expenses_before_inventory_rename'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='schedule_envelope',
            field=models.JSONField(blank=True, help_text='Per-worker weekly working pattern for the schedule (canonical {"mon": [["08:00", "17:00"]], …} shape). NULL means the worker uses the shop default (the schedule_week_envelope Configuration key). Validated by apps.schedule.calendar_arithmetic.', null=True),
        ),
    ]
