# Generated by Django 5.2.6 on 2026-07-25 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_seed_setup_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingcategory',
            name='is_deposit',
            field=models.BooleanField(default=False),
        ),
    ]
