# Generated by Django 5.2.5 on 2026-02-26 18:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('inventory_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('units', models.CharField(blank=True, default='sq ft', max_length=50)),
                ('qty_on_hand', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('qty_sold', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('qty_wasted', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
