# Generated by Django 5.2.6 on 2026-03-08 02:13

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceListItem',
            fields=[
                ('price_list_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('units', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('qty_on_hand', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('qty_sold', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('qty_wasted', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_inventoried', models.BooleanField(default=False)),
                ('line_item_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='price_list_items', to='core.lineitemtype')),
            ],
            options={
                'db_table': 'price_list',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('sell_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('line_item_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.lineitemtype')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='jobs.task')),
                ('price_list_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.pricelistitem')),
            ],
            options={
                'db_table': 'materials',
            },
        ),
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('adjustment_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_change', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('price_list_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.pricelistitem')),
            ],
            options={
                'db_table': 'inv_adjustments',
            },
        ),
        migrations.CreateModel(
            name='Earmark',
            fields=[
                ('earmark_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('price_list_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.pricelistitem')),
            ],
            options={
                'db_table': 'earmarks',
                'unique_together': {('price_list_item', 'job')},
            },
        ),
    ]
