# Generated by Django 5.2.6 on 2026-10-06 21:05

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('estimates', '0002_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateMaterialAssociation',
            fields=[
                ('template_material_association_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'template_material_assoc',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('inventory_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('qbo_id', models.CharField(blank=True, default='', max_length=50)),
                ('units', models.CharField(default='none', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('qty_on_hand', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('qty_sold', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('qty_wasted', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('accounting_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='core.accountingcategory')),
            ],
            options={
                'db_table': 'inventory_item',
            },
        ),
        migrations.CreateModel(
            name='Earmark',
            fields=[
                ('earmark_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem')),
            ],
            options={
                'db_table': 'earmarks',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('units', models.CharField(default='none', max_length=50)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('sell_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('consumption_state', models.CharField(choices=[('pending', 'Pending'), ('consumed', 'Consumed'), ('released', 'Released')], default='pending', max_length=20)),
                ('released_qty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Quantity restocked/released back out of the plan. quantity + released_qty = originally planned.', max_digits=10)),
                ('cost_source', models.CharField(blank=True, choices=[('estimated', 'Estimated'), ('entered', 'Entered'), ('po', 'PO'), ('expense', 'Expense'), ('customer_supplied', 'Customer supplied')], help_text='Cost provenance; NULL means provisional (unpriced).', max_length=20, null=True)),
                ('accounting_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.accountingcategory')),
                ('descoped_by', models.ForeignKey(blank=True, help_text="Accepted change order whose remove struck the agreement line this atom backed. Stamped at CO acceptance; drives the billing pool's 'descoped' badge.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='estimates.changeorder')),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventoryitem')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='jobs.job')),
            ],
            options={
                'db_table': 'materials',
            },
        ),
    ]
