# Generated by Django 5.2.6 on 2026-10-06 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estimates', '0003_initial'),
        ('inventory', '0001_initial'),
        ('jobs', '0001_initial'),
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='po_line_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='purchasing.purchaseorderlineitem'),
        ),
        migrations.AddField(
            model_name='material',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='jobs.task'),
        ),
        migrations.AddField(
            model_name='templatematerialassociation',
            name='inventory_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='templatematerialassociation',
            name='template_task_association',
            field=models.ForeignKey(blank=True, help_text='If set, generated material attaches to the corresponding generated Task.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_associations', to='estimates.templatetaskassociation'),
        ),
        migrations.AddField(
            model_name='templatematerialassociation',
            name='work_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_associations', to='estimates.worktemplate'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('qty_on_hand__gte', 0)), name='price_list_qty_on_hand_non_negative'),
        ),
        migrations.AlterUniqueTogether(
            name='earmark',
            unique_together={('inventory_item', 'job')},
        ),
    ]
