# Generated by Django 5.2.5 on 2026-02-26 18:15

from django.db import migrations


def copy_inventory_items(apps, schema_editor):
    PriceListItem = apps.get_model('invoicing', 'PriceListItem')
    InventoryItem = apps.get_model('inventory', 'InventoryItem')

    for pli in PriceListItem.objects.filter(is_inventoried=True):
        InventoryItem.objects.create(
            code=pli.code,
            description=pli.description,
            units=pli.units,
            qty_on_hand=pli.qty_on_hand,
            qty_sold=pli.qty_sold,
            qty_wasted=pli.qty_wasted,
            purchase_price=pli.purchase_price,
            selling_price=pli.selling_price,
            is_active=pli.is_active,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('invoicing', '0013_alter_pricelistitem_units'),
    ]

    operations = [
        migrations.RunPython(copy_inventory_items, migrations.RunPython.noop),
    ]
