# Generated by Django 5.2.6 on 2026-03-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelistitem',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
