# Generated by Django 5.2.6 on 2026-03-07 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_copy_pricelist_to_inventory'),
        ('invoicing', '0017_pricelistitem_is_inventoried'),
        ('jobs', '0034_material_estimatelineitem_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='Earmark',
            fields=[
                ('earmark_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('price_list_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicing.pricelistitem')),
            ],
            options={
                'unique_together': {('price_list_item', 'job')},
            },
        ),
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('adjustment_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_change', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('price_list_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicing.pricelistitem')),
            ],
        ),
        migrations.DeleteModel(
            name='InventoryItem',
        ),
    ]
