# Generated by Django 5.2.6 on 2026-03-29 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_lineitemtype_to_accountingcategory'),
        ('inventory', '0002_alter_pricelistitem_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='line_item_type',
            new_name='accounting_category',
        ),
        migrations.RenameField(
            model_name='pricelistitem',
            old_name='line_item_type',
            new_name='accounting_category',
        ),
    ]
