# Generated by Django 5.2.6 on 2026-03-31 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_line_item_type_material_accounting_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelistitem',
            name='units',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
