# Generated by Django 5.2.6 on 2026-04-05 20:25

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_user_options'),
        ('inventory', '0004_alter_pricelistitem_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanMaterial',
            fields=[
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('sell_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('plan_material_id', models.AutoField(primary_key=True, serialize=False)),
                ('accounting_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.accountingcategory')),
            ],
            options={
                'db_table': 'plan_materials',
            },
        ),
    ]
