# Generated by Django 5.2.6 on 2026-04-05 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_planmaterial'),
        ('jobs', '0008_task_bundle_material_split'),
    ]

    operations = [
        migrations.AddField(
            model_name='planmaterial',
            name='plan_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_materials', to='jobs.plantask'),
        ),
        migrations.AddField(
            model_name='planmaterial',
            name='price_list_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.pricelistitem'),
        ),
    ]
