# Generated by Django 5.2.6 on 2026-04-09 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_user_options'),
        ('inventory', '0006_planmaterial_plan_task_planmaterial_price_list_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelistitem',
            name='accounting_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_list_items', to='core.accountingcategory'),
        ),
    ]
