# Generated by Django 5.2.6 on 2026-04-15 05:57

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_pricelistitem_accounting_category'),
        ('jobs', '0012_remove_task_work_order_job_template_task_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='consumption_state',
            field=models.CharField(choices=[('na', 'N/A'), ('pending', 'Pending'), ('consumed', 'Consumed')], default='na', max_length=20),
        ),
        migrations.AddField(
            model_name='material',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='material',
            name='restocked_qty',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
