# Generated by Django 5.2.6 on 2026-04-15 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0009_rename_workordertemplate_worktemplate_and_more'),
        ('inventory', '0008_material_job_plan_worksheet_additive'),
    ]

    operations = [
        migrations.AddField(
            model_name='planmaterial',
            name='est_worksheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_materials', to='estimates.estworksheet'),
        ),
    ]
