# Generated by Django 5.2.6 on 2026-04-15 06:01

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_retire_can_approve_expenses'),
        ('estimates', '0009_rename_workordertemplate_worktemplate_and_more'),
        ('inventory', '0009_plan_material_est_worksheet_additive'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateMaterial',
            fields=[
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('sell_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('template_material_id', models.AutoField(primary_key=True, serialize=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('accounting_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.accountingcategory')),
                ('price_list_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.pricelistitem')),
                ('work_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='estimates.worktemplate')),
            ],
            options={
                'db_table': 'template_materials',
                'ordering': ['sort_order'],
            },
        ),
    ]
