# Generated by Django 5.2.6 on 2026-04-15 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_add_template_material'),
        ('jobs', '0012_remove_task_work_order_job_template_task_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='jobs.task'),
        ),
    ]
