# Generated by Django 5.2.6 on 2026-04-15 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_material_task_nullable'),
        ('jobs', '0012_remove_task_work_order_job_template_task_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planmaterial',
            name='plan_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_materials', to='jobs.plantask'),
        ),
    ]
