# Generated by Django 5.2.6 on 2026-04-16 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_consumption_state_na_backfill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='consumption_state',
            field=models.CharField(choices=[('pending', 'Pending'), ('consumed', 'Consumed')], default='pending', max_length=20),
        ),
    ]
