# Generated by Django 5.2.6 on 2026-04-18 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_material_consumption_state'),
        ('purchasing', '0006_remove_purchaseorderlineitem_cancelled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='po_line_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='purchasing.purchaseorderlineitem'),
        ),
    ]
