# Generated by Django 5.2.6 on 2026-05-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_material_source_plan_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='units',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='planmaterial',
            name='units',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='templatematerial',
            name='units',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
