# Generated by Django 5.2.6 on 2026-05-09 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0019_drop_workitem_ac_fields'),
        ('inventory', '0019_material_units_planmaterial_units_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateMaterialAssociation',
            fields=[
                ('template_material_association_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sort_order', models.IntegerField(default=0)),
                ('price_list_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.pricelistitem')),
                ('template_task_association', models.ForeignKey(blank=True, help_text='If set, generated material attaches to the corresponding generated PlanTask/Task.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_associations', to='estimates.templatetaskassociation')),
                ('work_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_associations', to='estimates.worktemplate')),
            ],
            options={
                'db_table': 'template_material_assoc',
                'ordering': ['sort_order'],
            },
        ),
    ]
