# Generated by Django 5.2.6 on 2026-05-09 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_backfill_template_material_assoc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemplateMaterial',
        ),
    ]
