# Generated by Django 5.2.6 on 2026-05-13 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_retire_can_approve_expenses'),
        ('inventory', '0024_alter_materialbase_accounting_category'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pricelistitem',
            constraint=models.CheckConstraint(condition=models.Q(('qty_on_hand__gte', 0)), name='price_list_qty_on_hand_non_negative'),
        ),
    ]
