# Generated by Django 5.2.6 on 2026-06-15 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_rename_pricelistitem_inventoryitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryAdjustment',
        ),
    ]
