# Generated by Django 5.2.6 on 2026-06-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_delete_inventoryadjustment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='is_inventoried',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='is_catalog',
            field=models.BooleanField(default=True),
        ),
    ]
