# Generated by Django 5.2.6 on 2026-06-16 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_inventoryhistory'),
        ('inventory', '0028_remove_inventoryitem_is_inventoried_and_more'),
        ('jobs', '0043_job_project_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='earmark',
            old_name='price_list_item',
            new_name='inventory_item',
        ),
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='price_list_item_id',
            new_name='inventory_item_id',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='price_list_item',
            new_name='inventory_item',
        ),
        migrations.RenameField(
            model_name='planmaterial',
            old_name='price_list_item',
            new_name='inventory_item',
        ),
        migrations.RenameField(
            model_name='templatematerialassociation',
            old_name='price_list_item',
            new_name='inventory_item',
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='accounting_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='core.accountingcategory'),
        ),
        migrations.AlterUniqueTogether(
            name='earmark',
            unique_together={('inventory_item', 'job')},
        ),
    ]
