# Generated by Django 5.2.6 on 2026-06-30 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0037_remove_estworksheet_job'),
        ('inventory', '0029_rename_price_list_item_earmark_inventory_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='source_plan_material',
        ),
        migrations.AlterField(
            model_name='templatematerialassociation',
            name='template_task_association',
            field=models.ForeignKey(blank=True, help_text='If set, generated material attaches to the corresponding generated Task.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_associations', to='estimates.templatetaskassociation'),
        ),
        migrations.DeleteModel(
            name='PlanMaterial',
        ),
    ]
