# Generated by Django 5.2.6 on 2026-07-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_material_released_qty_rename_and_released_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='cost_source',
            field=models.CharField(blank=True, choices=[('estimated', 'Estimated'), ('entered', 'Entered'), ('po', 'PO'), ('expense', 'Expense'), ('customer_supplied', 'Customer supplied')], help_text='Cost provenance; NULL means provisional (unpriced).', max_length=20, null=True),
        ),
    ]
