# Generated by Django 5.2.6 on 2026-07-05 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_material_cost_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='is_catalog',
        ),
    ]
