# Generated by Django 5.2.6 on 2026-07-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_remove_inventoryitem_is_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='qbo_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
