# Generated by Django 5.2.6 on 2026-08-09 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0046_changeorderlineitem_adjustment_percent_and_more'),
        ('inventory', '0034_inventoryitem_qbo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='descoped_by',
            field=models.ForeignKey(blank=True, help_text="Accepted change order whose remove struck the agreement line this atom backed. Stamped at CO acceptance; drives the billing pool's 'descoped' badge.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='estimates.changeorder'),
        ),
    ]
