# Generated by Django 5.2.6 on 2026-10-06 21:05

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('estimates', '0002_initial'),
        ('inventory', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('cancelled', 'Cancelled'), ('superseded', 'Superseded'), ('partly-paid', 'Partly Paid'), ('paid', 'Paid in Full'), ('defaulted', 'Defaulted')], default='draft', max_length=20)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('closed_date', models.DateTimeField(blank=True, null=True)),
                ('qbo_id', models.CharField(max_length=50, null=True)),
                ('qbo_payment_status', models.CharField(blank=True, default='', max_length=50)),
                ('qbo_amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
            ],
            options={
                'db_table': 'invoices',
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('line_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('line_number', models.PositiveIntegerField(blank=True, null=True)),
                ('qty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('units', models.CharField(default='none', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_comment', models.BooleanField(default=False, help_text='Informational line only — no charge, not linked to any task/atom.')),
                ('adjustment_percent', models.DecimalField(blank=True, decimal_places=2, help_text="Snapshot of adjustment_service's rate at creation time. compute_adjustment_amount reads this field, never the live scheme.", max_digits=6, null=True)),
                ('accounting_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to='core.accountingcategory')),
                ('adjustment_service', models.ForeignKey(blank=True, help_text='Set when this line is a percentage adjustment (rush/discount).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='jobs.ratescheme')),
                ('adjustment_target_categories', models.ManyToManyField(blank=True, help_text='Categories the adjustment applies to; empty = all non-adjustment lines.', related_name='+', to='core.accountingcategory')),
                ('agreement_co_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='estimates.changeorderlineitem')),
                ('agreement_estimate_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='estimates.estimatelineitem')),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryitem')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicing.invoice')),
            ],
            options={
                'verbose_name': 'Invoice Line Item',
                'verbose_name_plural': 'Invoice Line Items',
                'db_table': 'invoice_li',
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItemSource',
            fields=[
                ('source_id', models.AutoField(primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('material', 'Material'), ('task', 'Task'), ('expense', 'Expense'), ('deposit', 'Deposit')], max_length=20)),
                ('source_pk', models.PositiveIntegerField()),
                ('invoice_line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='invoicing.invoicelineitem')),
            ],
            options={
                'db_table': 'invoice_line_item_sources',
            },
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'draft')), fields=('job',), name='unique_draft_invoice_per_job'),
        ),
        migrations.AlterUniqueTogether(
            name='invoicelineitemsource',
            unique_together={('source_type', 'source_pk')},
        ),
    ]
