# Generated by Django 5.2.6 on 2026-03-29 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_lineitemtype_to_accountingcategory'),
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicelineitem',
            old_name='line_item_type',
            new_name='accounting_category',
        ),
    ]
