# Generated by Django 5.2.6 on 2026-03-29 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0002_rename_line_item_type_invoicelineitem_accounting_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='qbo_amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='qbo_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='qbo_payment_status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
