# Generated by Django 5.2.6 on 2026-03-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0003_invoice_qbo_amount_paid_invoice_qbo_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='qbo_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
