# Generated by Django 5.2.6 on 2026-03-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0004_alter_invoice_qbo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='qbo_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
