# Generated by Django 5.2.6 on 2026-03-31 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0005_alter_invoice_qbo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicelineitem',
            name='units',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
