# Generated by Django 5.2.6 on 2026-04-10 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0006_alter_invoicelineitem_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceLineItemSource',
            fields=[
                ('source_id', models.AutoField(primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('blep', 'Blep'), ('material', 'Material')], max_length=20)),
                ('source_pk', models.PositiveIntegerField()),
                ('invoice_line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='invoicing.invoicelineitem')),
            ],
            options={
                'db_table': 'invoice_line_item_sources',
                'unique_together': {('source_type', 'source_pk')},
            },
        ),
    ]
