# Generated by Django 5.2.6 on 2026-04-10 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0008_unique_draft_invoice_per_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicelineitem',
            name='task',
        ),
    ]
