# Generated by Django 5.2.6 on 2026-05-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0009_remove_invoicelineitem_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicelineitemsource',
            name='source_type',
            field=models.CharField(choices=[('blep', 'Blep'), ('material', 'Material'), ('task', 'Task')], max_length=20),
        ),
    ]
