# Generated by Django 5.2.6 on 2026-05-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0010_add_source_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicelineitemsource',
            name='source_type',
            field=models.CharField(choices=[('material', 'Material'), ('task', 'Task')], max_length=20),
        ),
    ]
