# Generated by Django 5.2.6 on 2026-02-01 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_line_item_type'),
        ('invoicing', '0011_pricelistitem_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='line_item_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to='core.lineitemtype'),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='tax_rate_override',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='taxable_override',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('cancelled', 'Cancelled'), ('superseded', 'Superseded'), ('partly-paid', 'Partly Paid'), ('paid', 'Paid in Full'), ('defaulted', 'Defaulted')], default='draft', max_length=20),
        ),
    ]
