# Generated by Django 5.2.6 on 2026-05-13 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0011_alter_invoicelineitemsource_source_type'),
        ('jobs', '0037_remove_job_template'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'draft')), fields=('job',), name='unique_draft_invoice_per_job'),
        ),
    ]
