# Generated by Django 5.2.5 on 2026-02-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0011_pricelistitem_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelistitem',
            name='is_inventoried',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('cancelled', 'Cancelled'), ('superseded', 'Superseded'), ('partly-paid', 'Partly Paid'), ('paid', 'Paid in Full'), ('defaulted', 'Defaulted')], default='draft', max_length=20),
        ),
    ]
