# Generated by Django 5.2.6 on 2026-02-01 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_line_item_type'),
        ('invoicing', '0012_add_tax_fields_to_line_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelistitem',
            name='line_item_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='price_list_items', to='core.lineitemtype'),
        ),
    ]
