# Generated by Django 5.2.6 on 2026-06-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0012_invoice_unique_draft_invoice_per_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicelineitemsource',
            name='source_type',
            field=models.CharField(choices=[('material', 'Material'), ('task', 'Task'), ('expense', 'Expense')], max_length=20),
        ),
    ]
