# Generated by Django 5.2.5 on 2026-02-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0012_pricelistitem_is_inventoried_alter_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelistitem',
            name='units',
            field=models.CharField(blank=True, default='sq ft', max_length=50),
        ),
    ]
