# Generated by Django 5.2.5 on 2026-02-26 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0013_alter_pricelistitem_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricelistitem',
            name='is_inventoried',
        ),
    ]
