# Generated by Django 5.2.6 on 2026-06-16 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0013_alter_invoicelineitemsource_source_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicelineitem',
            old_name='price_list_item',
            new_name='inventory_item',
        ),
    ]
