# Generated by Django 5.2.6 on 2026-02-12 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0013_add_line_item_type_fk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicelineitem',
            old_name='price_currency',
            new_name='price',
        ),
    ]
