# Generated by Django 5.2.6 on 2026-06-24 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_expenseshistory'),
        ('invoicing', '0014_rename_price_list_item_invoicelineitem_inventory_item'),
        ('jobs', '0046_alter_serviceprice_algorithm'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='adjustment_service',
            field=models.ForeignKey(blank=True, help_text='Set when this line is a percentage adjustment (rush/discount).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='jobs.serviceprice'),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='adjustment_target_categories',
            field=models.ManyToManyField(blank=True, help_text='Categories the adjustment applies to; empty = all non-adjustment lines.', related_name='+', to='core.accountingcategory'),
        ),
    ]
