# Generated by Django 5.2.5 on 2026-02-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0014_remove_pricelistitem_is_inventoried'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelistitem',
            name='units',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
