# Generated by Django 5.2.5 on 2026-02-26 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0014_rename_price_currency_to_price'),
        ('invoicing', '0015_alter_pricelistitem_units'),
    ]

    operations = [
    ]
