# Generated by Django 5.2.6 on 2026-03-07 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0016_merge_20260226_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelistitem',
            name='is_inventoried',
            field=models.BooleanField(default=False),
        ),
    ]
