# Generated by Django 5.2.6 on 2026-06-30 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0017_alter_invoicelineitem_adjustment_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicelineitemsource',
            name='source_type',
            field=models.CharField(choices=[('material', 'Material'), ('task', 'Task'), ('expense', 'Expense'), ('fee', 'Fee')], max_length=20),
        ),
    ]
