# Generated by Django 5.2.6 on 2026-07-22 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0019_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicelineitem',
            name='tax_rate_override',
        ),
        migrations.RemoveField(
            model_name='invoicelineitem',
            name='taxable_override',
        ),
    ]
