# Generated by Django 5.2.6 on 2026-07-25 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0020_remove_invoicelineitem_tax_rate_override_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicelineitemsource',
            name='source_type',
            field=models.CharField(choices=[('material', 'Material'), ('task', 'Task'), ('expense', 'Expense'), ('fee', 'Fee'), ('deposit', 'Deposit')], max_length=20),
        ),
    ]
