# Generated by Django 5.2.6 on 2026-08-16 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0021_alter_invoicelineitemsource_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='is_comment',
            field=models.BooleanField(default=False, help_text='Informational line only — no charge, not linked to any task/atom.'),
        ),
    ]
