# Generated by Django 5.2.6 on 2026-08-03 04:28

from django.db import migrations, models


def forwards(apps, schema_editor):
    """Backfill adjustment_percent from adjustment_service.rate for existing
    adjustment lines (task-owned-money Phase 1, Task 5). New rows get the
    field populated at creation time by InvoiceService.add_adjustment_line /
    copy_from_estimate; this covers rows written before that existed.

    Idempotent: re-running just re-derives the same value from the same FK,
    so it's safe to run twice.
    """
    InvoiceLineItem = apps.get_model('invoicing', 'InvoiceLineItem')
    for line in InvoiceLineItem.objects.filter(adjustment_service__isnull=False).select_related('adjustment_service'):
        line.adjustment_percent = line.adjustment_service.rate
        line.save(update_fields=['adjustment_percent'])


def backwards(apps, schema_editor):
    # Reverse leaves adjustment_percent populated. It's additive snapshot
    # data the pre-migration schema never read, so there's nothing to undo.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0021_alter_invoicelineitemsource_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='adjustment_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Snapshot of adjustment_service's rate at creation time. compute_adjustment_amount reads this field, never the live scheme.", max_digits=6, null=True),
        ),
        migrations.RunPython(forwards, backwards),
    ]
