# Generated by Django 5.2.6 on 2026-08-08 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0044_estimatelineitem_adjustment_percent'),
        ('invoicing', '0022_invoicelineitem_adjustment_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='agreement_co_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='estimates.changeorderlineitem'),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='agreement_estimate_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='estimates.estimatelineitem'),
        ),
    ]
