# Generated by Django 5.2.6 on 2026-08-09 19:56
#
# Fee removal (spec docs/plans/2026-08-06-better-fees.md §10 phase 5):
# purge the legacy 'fee' source rows BEFORE the source_type choices narrow,
# so no row carries a value outside the new choice set. Reverse is a noop —
# fee data is unrecoverable by design (claimed lines already carry their
# stored values; the source rows were provenance-only and die with the
# Fee atom, dropped in jobs/0062_delete_fee which depends on this migration).

from django.db import migrations, models


def drop_fee_sources(apps, schema_editor):
    # Spec 2026-08-06-better-fees §10 phase 5: claimed lines already carry
    # their stored values; the fee source rows are provenance-only and die
    # with the Fee atom. Historical models have no custom delete(), so
    # QuerySet.delete() is correct here.
    apps.get_model('invoicing', 'InvoiceLineItemSource').objects.filter(source_type='fee').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0023_invoicelineitem_agreement_co_line_and_more'),
    ]

    operations = [
        migrations.RunPython(drop_fee_sources, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='invoicelineitemsource',
            name='source_type',
            field=models.CharField(choices=[('material', 'Material'), ('task', 'Task'), ('expense', 'Expense'), ('deposit', 'Deposit')], max_length=20),
        ),
    ]
