# Generated by Django 5.2.6 on 2026-08-16 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # Re-parented in the 2026-09-21 merge of origin/main (0022->0025).
        ('invoicing', '0024_alter_invoicelineitemsource_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='is_comment',
            field=models.BooleanField(default=False, help_text='Informational line only — no charge, not linked to any task/atom.'),
        ),
    ]
