"""
Django settings for minibini project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-change-this-in-production'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'testserver',
    'localhost',
    '127.0.0.1',
    'minibini.me',
    '45.33.56.130'
]

CSRF_TRUSTED_ORIGINS = [
    'https://minibini.me',
    'http://localhost:9000',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.core',
    'apps.jobs',
    'apps.estimates',
    'apps.contacts',
    'apps.invoicing',
    'apps.purchasing',
    'apps.search',
    'apps.inventory',
    'apps.qbo',
    'rest_framework',
    'apps.api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'apps.core.middleware.HistoryMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'minibini.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'minibini.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv("DATABASE_NAME", "minibini_db"),
        'USER': os.getenv("DATABASE_USER", "minibini_user"),
        'PASSWORD': os.getenv("DATABASE_PASSWORD", "dev_password"),
        'HOST': os.getenv("DATABASE_HOST", "localhost"),
        'PORT': '3306',
    }
}


# Email settings
# WARNING: Move to environment variables for production
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'minibini.test@gmail.com')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')

# IMAP (inbound email fetch)
EMAIL_IMAP_SERVER = 'imap.gmail.com'
EMAIL_IMAP_FOLDER = 'INBOX'  # Default folder to monitor
EMAIL_IMAP_SSL = True  # Use SSL/TLS (port 993)
EMAIL_IMAP_PORT = None  # None = auto-detect (993 for SSL, 143 for non-SSL)

# SMTP (outbound email)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# QuickBooks Online Integration
QBO_CLIENT_ID = os.environ.get('QBO_CLIENT_ID', '')
QBO_CLIENT_SECRET = os.environ.get('QBO_CLIENT_SECRET', '')
QBO_REDIRECT_URI = os.environ.get('QBO_REDIRECT_URI', 'http://localhost:8000/api/qbo/callback/')
QBO_ENVIRONMENT = os.environ.get('QBO_ENVIRONMENT', 'sandbox')  # 'sandbox' or 'production'
SPA_BASE_URL = os.environ.get('SPA_BASE_URL', 'http://localhost:9000')  # dev: 'http://localhost:9000', prod: '' (same origin)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files (user uploads)
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model - MUST be set before any migrations
AUTH_USER_MODEL = 'core.User'

# Fixture directories
FIXTURE_DIRS = [
    BASE_DIR / 'fixtures',
]

# Session settings
SESSION_COOKIE_AGE = 86400  # 1 day (24 * 60 * 60 seconds) instead of default 14 days

LOGIN_URL = '/admin/login/'  # Interim — Django admin login form until SPA login page exists

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'apps.api.pagination.StandardPagination',
    'PAGE_SIZE': 25,
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'WARNING',
        },
    },
}
