# Generated by Django 5.2.6 on 2026-10-06 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reimbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qbo_id', models.CharField(blank=True, default='', max_length=50)),
                ('qbo_sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced to QBO'), ('sync_failed', 'QBO sync failed')], default='pending', max_length=20)),
                ('qbo_sync_error', models.TextField(blank=True, default='')),
                ('qbo_pending_op', models.CharField(blank=True, choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], default='', max_length=10)),
                ('paid_on', models.DateField()),
                ('payment_account_id', models.CharField(max_length=50)),
                ('reference_number', models.CharField(blank=True, default='', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reimbursements',
                'ordering': ['-paid_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qbo_id', models.CharField(blank=True, default='', max_length=50)),
                ('qbo_sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced to QBO'), ('sync_failed', 'QBO sync failed')], default='pending', max_length=20)),
                ('qbo_sync_error', models.TextField(blank=True, default='')),
                ('qbo_pending_op', models.CharField(blank=True, choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], default='', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchased_on', models.DateField()),
                ('description', models.TextField(blank=True, default='')),
                ('payment_method', models.CharField(choices=[('company', 'Company'), ('personal', 'Personal (reimbursement)')], max_length=20)),
                ('payment_account_id', models.CharField(blank=True, default='', max_length=50)),
                ('reference_number', models.CharField(blank=True, default='', max_length=50)),
                ('stock_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('reimbursed', 'Reimbursed'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accounting_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.accountingcategory')),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entered_expenses', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='jobs.job')),
            ],
            options={
                'db_table': 'expenses',
                'ordering': ['-purchased_on', '-created_at'],
            },
        ),
    ]
