# Generated by Django 5.2.6 on 2026-04-12 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0011_retire_can_approve_expenses'),
        ('inventory', '0007_alter_pricelistitem_accounting_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reimbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_on', models.DateField()),
                ('payment_account_id', models.CharField(max_length=50)),
                ('reference_number', models.CharField(blank=True, default='', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced to QBO'), ('sync_failed', 'QBO sync failed')], default='pending', max_length=20)),
                ('qbo_id', models.CharField(blank=True, default='', max_length=50)),
                ('qbo_sync_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_reimbursements', to=settings.AUTH_USER_MODEL)),
                ('purchased_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reimbursements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reimbursements',
                'ordering': ['-paid_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchased_on', models.DateField()),
                ('description', models.TextField(blank=True, default='')),
                ('payment_method', models.CharField(choices=[('company', 'Company'), ('personal', 'Personal (reimbursement)')], max_length=20)),
                ('payment_account_id', models.CharField(blank=True, default='', max_length=50)),
                ('reference_number', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('reimbursed', 'Reimbursed'), ('rejected', 'Rejected'), ('synced', 'Synced to QBO'), ('sync_failed', 'QBO sync failed')], default='submitted', max_length=20)),
                ('qbo_id', models.CharField(blank=True, default='', max_length=50)),
                ('qbo_sync_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accounting_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.accountingcategory')),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entered_expenses', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='inventory.material')),
                ('purchased_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchased_expenses', to=settings.AUTH_USER_MODEL)),
                ('reimbursement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.reimbursement')),
            ],
            options={
                'db_table': 'expenses',
                'ordering': ['-purchased_on', '-created_at'],
            },
        ),
    ]
