# Generated by Django 5.2.6 on 2026-06-14 07:08

import django.db.models.deletion
from django.db import migrations, models


def backfill_job_from_material(apps, schema_editor):
    """Set Expense.job from the linked material's job (legacy fallback:
    material.task.job) for existing rows that have a material but no job yet."""
    Expense = apps.get_model('expenses', 'Expense')
    qs = (
        Expense.objects
        .filter(material__isnull=False, job__isnull=True)
        .select_related('material', 'material__task')
    )
    for exp in qs:
        mat = exp.material
        job_id = mat.job_id or (mat.task.job_id if mat.task_id else None)
        if job_id:
            exp.job_id = job_id
            exp.save(update_fields=['job'])


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        ('jobs', '0043_job_project_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='jobs.job'),
        ),
        migrations.RunPython(
            backfill_job_from_material,
            migrations.RunPython.noop,
        ),
    ]
