# Generated by Django 5.2.6 on 2026-06-14 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_job'),
        ('inventory', '0025_pricelistitem_price_list_qty_on_hand_non_negative'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='stock_pli',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.pricelistitem'),
        ),
        migrations.AddField(
            model_name='expense',
            name='stock_qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
