# Generated by Django 5.2.6 on 2026-06-22 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expense_stock_pli_expense_stock_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reimbursement',
            old_name='status',
            new_name='qbo_sync_status',
        ),
    ]
