# Generated by Django 5.2.6 on 2026-06-22 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_rename_status_reimbursement_qbo_sync_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='qbo_sync_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced to QBO'), ('sync_failed', 'QBO sync failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('reimbursed', 'Reimbursed'), ('rejected', 'Rejected')], default='submitted', max_length=20),
        ),
    ]
