# Generated by Django 5.2.6 on 2026-06-22 04:41

from django.db import migrations


def forward(apps, schema_editor):
    Expense = apps.get_model('expenses', 'Expense')
    for e in Expense.objects.filter(status__in=['synced', 'sync_failed']):
        e.qbo_sync_status = e.status  # 'synced' or 'sync_failed'
        e.status = 'submitted'
        e.save(update_fields=['status', 'qbo_sync_status'])


def backward(apps, schema_editor):
    Expense = apps.get_model('expenses', 'Expense')
    for e in Expense.objects.filter(qbo_sync_status__in=['synced', 'sync_failed']):
        e.status = e.qbo_sync_status
        e.save(update_fields=['status'])


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_expense_qbo_sync_status_alter_expense_status'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
