# Generated by Django 5.2.6 on 2026-06-22 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_expense_status_split'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='qbo_pending_op',
            field=models.CharField(blank=True, choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='qbo_pending_op',
            field=models.CharField(blank=True, choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], default='', max_length=10),
        ),
    ]
